/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Anvisa {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Anvisa(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Anvisa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Anvisa(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Anvisa_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Anvisa_cod_erro_get(swigCPtr, this);
  }

  public void setTam_lista_atividades_classes(int value) {
    knuJNI.Anvisa_tam_lista_atividades_classes_set(swigCPtr, this, value);
  }

  public int getTam_lista_atividades_classes() {
    return knuJNI.Anvisa_tam_lista_atividades_classes_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Anvisa_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Anvisa_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.Anvisa_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.Anvisa_cnpj_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.Anvisa_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.Anvisa_razao_get(swigCPtr, this);
  }

  public void setEndereco(String value) {
    knuJNI.Anvisa_endereco_set(swigCPtr, this, value);
  }

  public String getEndereco() {
    return knuJNI.Anvisa_endereco_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.Anvisa_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.Anvisa_telefone_get(swigCPtr, this);
  }

  public void setResponsavel_tecnico(String value) {
    knuJNI.Anvisa_responsavel_tecnico_set(swigCPtr, this, value);
  }

  public String getResponsavel_tecnico() {
    return knuJNI.Anvisa_responsavel_tecnico_get(swigCPtr, this);
  }

  public void setResponsavel_legal(String value) {
    knuJNI.Anvisa_responsavel_legal_set(swigCPtr, this, value);
  }

  public String getResponsavel_legal() {
    return knuJNI.Anvisa_responsavel_legal_get(swigCPtr, this);
  }

  public void setCadastro(String value) {
    knuJNI.Anvisa_cadastro_set(swigCPtr, this, value);
  }

  public String getCadastro() {
    return knuJNI.Anvisa_cadastro_get(swigCPtr, this);
  }

  public void setNumero_cadastro(String value) {
    knuJNI.Anvisa_numero_cadastro_set(swigCPtr, this, value);
  }

  public String getNumero_cadastro() {
    return knuJNI.Anvisa_numero_cadastro_get(swigCPtr, this);
  }

  public void setData_cadastro(String value) {
    knuJNI.Anvisa_data_cadastro_set(swigCPtr, this, value);
  }

  public String getData_cadastro() {
    return knuJNI.Anvisa_data_cadastro_get(swigCPtr, this);
  }

  public void setSituacao(String value) {
    knuJNI.Anvisa_situacao_set(swigCPtr, this, value);
  }

  public String getSituacao() {
    return knuJNI.Anvisa_situacao_get(swigCPtr, this);
  }

  public void setNumero_processo(String value) {
    knuJNI.Anvisa_numero_processo_set(swigCPtr, this, value);
  }

  public String getNumero_processo() {
    return knuJNI.Anvisa_numero_processo_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Anvisa_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Anvisa_html_get(swigCPtr, this);
  }

  public String getAtividadeClasses(int index) {
    return knuJNI.Anvisa_getAtividadeClasses(swigCPtr, this, index);
  }

  public Anvisa() {
    this(knuJNI.new_Anvisa(), true);
  }

}
