/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Cadesp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Cadesp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cadesp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Cadesp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Cadesp_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Cadesp_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Cadesp_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Cadesp_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.Cadesp_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.Cadesp_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.Cadesp_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.Cadesp_ie_get(swigCPtr, this);
  }

  public void setNome_empresarial(String value) {
    knuJNI.Cadesp_nome_empresarial_set(swigCPtr, this, value);
  }

  public String getNome_empresarial() {
    return knuJNI.Cadesp_nome_empresarial_get(swigCPtr, this);
  }

  public void setNome_fantasia(String value) {
    knuJNI.Cadesp_nome_fantasia_set(swigCPtr, this, value);
  }

  public String getNome_fantasia() {
    return knuJNI.Cadesp_nome_fantasia_get(swigCPtr, this);
  }

  public void setNatureza_juridica(String value) {
    knuJNI.Cadesp_natureza_juridica_set(swigCPtr, this, value);
  }

  public String getNatureza_juridica() {
    return knuJNI.Cadesp_natureza_juridica_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.Cadesp_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.Cadesp_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.Cadesp_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.Cadesp_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.Cadesp_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.Cadesp_complemento_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.Cadesp_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.Cadesp_cep_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.Cadesp_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.Cadesp_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.Cadesp_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.Cadesp_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.Cadesp_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.Cadesp_uf_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.Cadesp_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.Cadesp_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.Cadesp_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.Cadesp_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setOcorrencia_fiscal(String value) {
    knuJNI.Cadesp_ocorrencia_fiscal_set(swigCPtr, this, value);
  }

  public String getOcorrencia_fiscal() {
    return knuJNI.Cadesp_ocorrencia_fiscal_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.Cadesp_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.Cadesp_atividade_economica_get(swigCPtr, this);
  }

  public void setRegime_apuracao(String value) {
    knuJNI.Cadesp_regime_apuracao_set(swigCPtr, this, value);
  }

  public String getRegime_apuracao() {
    return knuJNI.Cadesp_regime_apuracao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Cadesp_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Cadesp_html_get(swigCPtr, this);
  }

  public Cadesp() {
    this(knuJNI.new_Cadesp(), true);
  }

}
