/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Cnh {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Cnh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cnh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Cnh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Cnh_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Cnh_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Cnh_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Cnh_desc_erro_get(swigCPtr, this);
  }

  public void setNome_mae(String value) {
    knuJNI.Cnh_nome_mae_set(swigCPtr, this, value);
  }

  public String getNome_mae() {
    return knuJNI.Cnh_nome_mae_get(swigCPtr, this);
  }

  public void setData_emissao(String value) {
    knuJNI.Cnh_data_emissao_set(swigCPtr, this, value);
  }

  public String getData_emissao() {
    return knuJNI.Cnh_data_emissao_get(swigCPtr, this);
  }

  public void setNome_condutor(String value) {
    knuJNI.Cnh_nome_condutor_set(swigCPtr, this, value);
  }

  public String getNome_condutor() {
    return knuJNI.Cnh_nome_condutor_get(swigCPtr, this);
  }

  public void setNumero_registro(String value) {
    knuJNI.Cnh_numero_registro_set(swigCPtr, this, value);
  }

  public String getNumero_registro() {
    return knuJNI.Cnh_numero_registro_get(swigCPtr, this);
  }

  public void setNumero_cnh(String value) {
    knuJNI.Cnh_numero_cnh_set(swigCPtr, this, value);
  }

  public String getNumero_cnh() {
    return knuJNI.Cnh_numero_cnh_get(swigCPtr, this);
  }

  public void setValidade_cnh(String value) {
    knuJNI.Cnh_validade_cnh_set(swigCPtr, this, value);
  }

  public String getValidade_cnh() {
    return knuJNI.Cnh_validade_cnh_get(swigCPtr, this);
  }

  public void setCategoria(String value) {
    knuJNI.Cnh_categoria_set(swigCPtr, this, value);
  }

  public String getCategoria() {
    return knuJNI.Cnh_categoria_get(swigCPtr, this);
  }

  public void setNumero_seguranca(String value) {
    knuJNI.Cnh_numero_seguranca_set(swigCPtr, this, value);
  }

  public String getNumero_seguranca() {
    return knuJNI.Cnh_numero_seguranca_get(swigCPtr, this);
  }

  public void setValido(int value) {
    knuJNI.Cnh_valido_set(swigCPtr, this, value);
  }

  public int getValido() {
    return knuJNI.Cnh_valido_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Cnh_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Cnh_html_get(swigCPtr, this);
  }

  public Cnh() {
    this(knuJNI.new_Cnh(), true);
  }

}
