/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Correios {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Correios(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Correios obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Correios(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Correios_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Correios_cod_erro_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.Correios_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.Correios_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.Correios_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.Correios_cep_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Correios_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Correios_desc_erro_get(swigCPtr, this);
  }

  public void setLocalidade(String value) {
    knuJNI.Correios_localidade_set(swigCPtr, this, value);
  }

  public String getLocalidade() {
    return knuJNI.Correios_localidade_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.Correios_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.Correios_logradouro_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.Correios_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.Correios_uf_get(swigCPtr, this);
  }

  public Correios() {
    this(knuJNI.new_Correios(), true);
  }

}
