/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Cte {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Cte(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cte obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Cte(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Cte_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Cte_cod_erro_get(swigCPtr, this);
  }

  public void setTam_ocorrencia(int value) {
    knuJNI.Cte_tam_ocorrencia_set(swigCPtr, this, value);
  }

  public int getTam_ocorrencia() {
    return knuJNI.Cte_tam_ocorrencia_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Cte_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Cte_desc_erro_get(swigCPtr, this);
  }

  public void setChave(String value) {
    knuJNI.Cte_chave_set(swigCPtr, this, value);
  }

  public String getChave() {
    return knuJNI.Cte_chave_get(swigCPtr, this);
  }

  public void setVersao_xml(String value) {
    knuJNI.Cte_versao_xml_set(swigCPtr, this, value);
  }

  public String getVersao_xml() {
    return knuJNI.Cte_versao_xml_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.Cte_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.Cte_numero_get(swigCPtr, this);
  }

  public void setSerie(String value) {
    knuJNI.Cte_serie_set(swigCPtr, this, value);
  }

  public String getSerie() {
    return knuJNI.Cte_serie_get(swigCPtr, this);
  }

  public void setData_emissao(String value) {
    knuJNI.Cte_data_emissao_set(swigCPtr, this, value);
  }

  public String getData_emissao() {
    return knuJNI.Cte_data_emissao_get(swigCPtr, this);
  }

  public void setValor_total_servico(String value) {
    knuJNI.Cte_valor_total_servico_set(swigCPtr, this, value);
  }

  public String getValor_total_servico() {
    return knuJNI.Cte_valor_total_servico_get(swigCPtr, this);
  }

  public void setBase_calculo_icms(String value) {
    knuJNI.Cte_base_calculo_icms_set(swigCPtr, this, value);
  }

  public String getBase_calculo_icms() {
    return knuJNI.Cte_base_calculo_icms_get(swigCPtr, this);
  }

  public void setValor_icms(String value) {
    knuJNI.Cte_valor_icms_set(swigCPtr, this, value);
  }

  public String getValor_icms() {
    return knuJNI.Cte_valor_icms_get(swigCPtr, this);
  }

  public void setCnpj_emitente(String value) {
    knuJNI.Cte_cnpj_emitente_set(swigCPtr, this, value);
  }

  public String getCnpj_emitente() {
    return knuJNI.Cte_cnpj_emitente_get(swigCPtr, this);
  }

  public void setRazao_social_emitente(String value) {
    knuJNI.Cte_razao_social_emitente_set(swigCPtr, this, value);
  }

  public String getRazao_social_emitente() {
    return knuJNI.Cte_razao_social_emitente_get(swigCPtr, this);
  }

  public void setIe_emitente(String value) {
    knuJNI.Cte_ie_emitente_set(swigCPtr, this, value);
  }

  public String getIe_emitente() {
    return knuJNI.Cte_ie_emitente_get(swigCPtr, this);
  }

  public void setUf_emitente(String value) {
    knuJNI.Cte_uf_emitente_set(swigCPtr, this, value);
  }

  public String getUf_emitente() {
    return knuJNI.Cte_uf_emitente_get(swigCPtr, this);
  }

  public void setCnpj_dest(String value) {
    knuJNI.Cte_cnpj_dest_set(swigCPtr, this, value);
  }

  public String getCnpj_dest() {
    return knuJNI.Cte_cnpj_dest_get(swigCPtr, this);
  }

  public void setRazao_social_dest(String value) {
    knuJNI.Cte_razao_social_dest_set(swigCPtr, this, value);
  }

  public String getRazao_social_dest() {
    return knuJNI.Cte_razao_social_dest_get(swigCPtr, this);
  }

  public void setIe_dest(String value) {
    knuJNI.Cte_ie_dest_set(swigCPtr, this, value);
  }

  public String getIe_dest() {
    return knuJNI.Cte_ie_dest_get(swigCPtr, this);
  }

  public void setUf_dest(String value) {
    knuJNI.Cte_uf_dest_set(swigCPtr, this, value);
  }

  public String getUf_dest() {
    return knuJNI.Cte_uf_dest_get(swigCPtr, this);
  }

  public void setCnpj_tomador(String value) {
    knuJNI.Cte_cnpj_tomador_set(swigCPtr, this, value);
  }

  public String getCnpj_tomador() {
    return knuJNI.Cte_cnpj_tomador_get(swigCPtr, this);
  }

  public void setRazao_social_tomador(String value) {
    knuJNI.Cte_razao_social_tomador_set(swigCPtr, this, value);
  }

  public String getRazao_social_tomador() {
    return knuJNI.Cte_razao_social_tomador_get(swigCPtr, this);
  }

  public void setIe_tomador(String value) {
    knuJNI.Cte_ie_tomador_set(swigCPtr, this, value);
  }

  public String getIe_tomador() {
    return knuJNI.Cte_ie_tomador_get(swigCPtr, this);
  }

  public void setUf_tomador(String value) {
    knuJNI.Cte_uf_tomador_set(swigCPtr, this, value);
  }

  public String getUf_tomador() {
    return knuJNI.Cte_uf_tomador_get(swigCPtr, this);
  }

  public void setCnpj_remetente(String value) {
    knuJNI.Cte_cnpj_remetente_set(swigCPtr, this, value);
  }

  public String getCnpj_remetente() {
    return knuJNI.Cte_cnpj_remetente_get(swigCPtr, this);
  }

  public void setRazao_social_remetente(String value) {
    knuJNI.Cte_razao_social_remetente_set(swigCPtr, this, value);
  }

  public String getRazao_social_remetente() {
    return knuJNI.Cte_razao_social_remetente_get(swigCPtr, this);
  }

  public void setIe_remetente(String value) {
    knuJNI.Cte_ie_remetente_set(swigCPtr, this, value);
  }

  public String getIe_remetente() {
    return knuJNI.Cte_ie_remetente_get(swigCPtr, this);
  }

  public void setUf_remetente(String value) {
    knuJNI.Cte_uf_remetente_set(swigCPtr, this, value);
  }

  public String getUf_remetente() {
    return knuJNI.Cte_uf_remetente_get(swigCPtr, this);
  }

  public void setModal(String value) {
    knuJNI.Cte_modal_set(swigCPtr, this, value);
  }

  public String getModal() {
    return knuJNI.Cte_modal_get(swigCPtr, this);
  }

  public void setTipo_servico(String value) {
    knuJNI.Cte_tipo_servico_set(swigCPtr, this, value);
  }

  public String getTipo_servico() {
    return knuJNI.Cte_tipo_servico_get(swigCPtr, this);
  }

  public void setForma_emissao(String value) {
    knuJNI.Cte_forma_emissao_set(swigCPtr, this, value);
  }

  public String getForma_emissao() {
    return knuJNI.Cte_forma_emissao_get(swigCPtr, this);
  }

  public void setFinalidade(String value) {
    knuJNI.Cte_finalidade_set(swigCPtr, this, value);
  }

  public String getFinalidade() {
    return knuJNI.Cte_finalidade_get(swigCPtr, this);
  }

  public void setNatureza_operacao(String value) {
    knuJNI.Cte_natureza_operacao_set(swigCPtr, this, value);
  }

  public String getNatureza_operacao() {
    return knuJNI.Cte_natureza_operacao_get(swigCPtr, this);
  }

  public void setCfop(String value) {
    knuJNI.Cte_cfop_set(swigCPtr, this, value);
  }

  public String getCfop() {
    return knuJNI.Cte_cfop_get(swigCPtr, this);
  }

  public void setDigest_value(String value) {
    knuJNI.Cte_digest_value_set(swigCPtr, this, value);
  }

  public String getDigest_value() {
    return knuJNI.Cte_digest_value_get(swigCPtr, this);
  }

  public void setInicio_prestacao(String value) {
    knuJNI.Cte_inicio_prestacao_set(swigCPtr, this, value);
  }

  public String getInicio_prestacao() {
    return knuJNI.Cte_inicio_prestacao_get(swigCPtr, this);
  }

  public void setFim_prestacao(String value) {
    knuJNI.Cte_fim_prestacao_set(swigCPtr, this, value);
  }

  public String getFim_prestacao() {
    return knuJNI.Cte_fim_prestacao_get(swigCPtr, this);
  }

  public void setSituacao_atual(String value) {
    knuJNI.Cte_situacao_atual_set(swigCPtr, this, value);
  }

  public String getSituacao_atual() {
    return knuJNI.Cte_situacao_atual_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.Cte_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.Cte_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Cte_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Cte_html_get(swigCPtr, this);
  }

  public String getOcorrencia(int index) {
    return knuJNI.Cte_getOcorrencia(swigCPtr, this, index);
  }

  public String getProtocolo(int index) {
    return knuJNI.Cte_getProtocolo(swigCPtr, this, index);
  }

  public String getAutorizacao(int index) {
    return knuJNI.Cte_getAutorizacao(swigCPtr, this, index);
  }

  public String getRecebimento(int index) {
    return knuJNI.Cte_getRecebimento(swigCPtr, this, index);
  }

  public Cte() {
    this(knuJNI.new_Cte(), true);
  }

}
