/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Cte {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Cte(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cte obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Cte(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Cte_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Cte_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Cte_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Cte_desc_erro_get(swigCPtr, this);
  }

  public void setXml(String value) {
    knuJNI.Cte_xml_set(swigCPtr, this, value);
  }

  public String getXml() {
    return knuJNI.Cte_xml_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Cte_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Cte_html_get(swigCPtr, this);
  }

  public void setHtml_impressao(String value) {
    knuJNI.Cte_html_impressao_set(swigCPtr, this, value);
  }

  public String getHtml_impressao() {
    return knuJNI.Cte_html_impressao_get(swigCPtr, this);
  }

  public Cte() {
    this(knuJNI.new_Cte(), true);
  }

}
