/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Denatran {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Denatran(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Denatran obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Denatran(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Denatran_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Denatran_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Denatran_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Denatran_desc_erro_get(swigCPtr, this);
  }

  public void setPlaca(String value) {
    knuJNI.Denatran_placa_set(swigCPtr, this, value);
  }

  public String getPlaca() {
    return knuJNI.Denatran_placa_get(swigCPtr, this);
  }

  public void setRenavam(String value) {
    knuJNI.Denatran_renavam_set(swigCPtr, this, value);
  }

  public String getRenavam() {
    return knuJNI.Denatran_renavam_get(swigCPtr, this);
  }

  public void setCpf_cnpj(String value) {
    knuJNI.Denatran_cpf_cnpj_set(swigCPtr, this, value);
  }

  public String getCpf_cnpj() {
    return knuJNI.Denatran_cpf_cnpj_get(swigCPtr, this);
  }

  public void setNome(String value) {
    knuJNI.Denatran_nome_set(swigCPtr, this, value);
  }

  public String getNome() {
    return knuJNI.Denatran_nome_get(swigCPtr, this);
  }

  public void setTipo(String value) {
    knuJNI.Denatran_tipo_set(swigCPtr, this, value);
  }

  public String getTipo() {
    return knuJNI.Denatran_tipo_get(swigCPtr, this);
  }

  public void setEspecie(String value) {
    knuJNI.Denatran_especie_set(swigCPtr, this, value);
  }

  public String getEspecie() {
    return knuJNI.Denatran_especie_get(swigCPtr, this);
  }

  public void setCarroceria(String value) {
    knuJNI.Denatran_carroceria_set(swigCPtr, this, value);
  }

  public String getCarroceria() {
    return knuJNI.Denatran_carroceria_get(swigCPtr, this);
  }

  public void setCategoria(String value) {
    knuJNI.Denatran_categoria_set(swigCPtr, this, value);
  }

  public String getCategoria() {
    return knuJNI.Denatran_categoria_get(swigCPtr, this);
  }

  public void setCombustivel(String value) {
    knuJNI.Denatran_combustivel_set(swigCPtr, this, value);
  }

  public String getCombustivel() {
    return knuJNI.Denatran_combustivel_get(swigCPtr, this);
  }

  public void setMarca_modelo(String value) {
    knuJNI.Denatran_marca_modelo_set(swigCPtr, this, value);
  }

  public String getMarca_modelo() {
    return knuJNI.Denatran_marca_modelo_get(swigCPtr, this);
  }

  public void setAno_fabricacao(String value) {
    knuJNI.Denatran_ano_fabricacao_set(swigCPtr, this, value);
  }

  public String getAno_fabricacao() {
    return knuJNI.Denatran_ano_fabricacao_get(swigCPtr, this);
  }

  public void setAno_modelo(String value) {
    knuJNI.Denatran_ano_modelo_set(swigCPtr, this, value);
  }

  public String getAno_modelo() {
    return knuJNI.Denatran_ano_modelo_get(swigCPtr, this);
  }

  public void setCor(String value) {
    knuJNI.Denatran_cor_set(swigCPtr, this, value);
  }

  public String getCor() {
    return knuJNI.Denatran_cor_get(swigCPtr, this);
  }

  public void setLotacao(String value) {
    knuJNI.Denatran_lotacao_set(swigCPtr, this, value);
  }

  public String getLotacao() {
    return knuJNI.Denatran_lotacao_get(swigCPtr, this);
  }

  public void setCapacidade_carga(String value) {
    knuJNI.Denatran_capacidade_carga_set(swigCPtr, this, value);
  }

  public String getCapacidade_carga() {
    return knuJNI.Denatran_capacidade_carga_get(swigCPtr, this);
  }

  public void setPotencia(String value) {
    knuJNI.Denatran_potencia_set(swigCPtr, this, value);
  }

  public String getPotencia() {
    return knuJNI.Denatran_potencia_get(swigCPtr, this);
  }

  public void setCilindradas(String value) {
    knuJNI.Denatran_cilindradas_set(swigCPtr, this, value);
  }

  public String getCilindradas() {
    return knuJNI.Denatran_cilindradas_get(swigCPtr, this);
  }

  public void setResticao_1(String value) {
    knuJNI.Denatran_resticao_1_set(swigCPtr, this, value);
  }

  public String getResticao_1() {
    return knuJNI.Denatran_resticao_1_get(swigCPtr, this);
  }

  public void setResticao_2(String value) {
    knuJNI.Denatran_resticao_2_set(swigCPtr, this, value);
  }

  public String getResticao_2() {
    return knuJNI.Denatran_resticao_2_get(swigCPtr, this);
  }

  public void setResticao_3(String value) {
    knuJNI.Denatran_resticao_3_set(swigCPtr, this, value);
  }

  public String getResticao_3() {
    return knuJNI.Denatran_resticao_3_get(swigCPtr, this);
  }

  public void setResticao_4(String value) {
    knuJNI.Denatran_resticao_4_set(swigCPtr, this, value);
  }

  public String getResticao_4() {
    return knuJNI.Denatran_resticao_4_get(swigCPtr, this);
  }

  public void setOcorrencia_roubo(String value) {
    knuJNI.Denatran_ocorrencia_roubo_set(swigCPtr, this, value);
  }

  public String getOcorrencia_roubo() {
    return knuJNI.Denatran_ocorrencia_roubo_get(swigCPtr, this);
  }

  public void setComunicacao_venda(String value) {
    knuJNI.Denatran_comunicacao_venda_set(swigCPtr, this, value);
  }

  public String getComunicacao_venda() {
    return knuJNI.Denatran_comunicacao_venda_get(swigCPtr, this);
  }

  public void setRestricao_judicial(String value) {
    knuJNI.Denatran_restricao_judicial_set(swigCPtr, this, value);
  }

  public String getRestricao_judicial() {
    return knuJNI.Denatran_restricao_judicial_get(swigCPtr, this);
  }

  public void setMulta_interestadual(String value) {
    knuJNI.Denatran_multa_interestadual_set(swigCPtr, this, value);
  }

  public String getMulta_interestadual() {
    return knuJNI.Denatran_multa_interestadual_get(swigCPtr, this);
  }

  public void setRecall(String value) {
    knuJNI.Denatran_recall_set(swigCPtr, this, value);
  }

  public String getRecall() {
    return knuJNI.Denatran_recall_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Denatran_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Denatran_html_get(swigCPtr, this);
  }

  public Denatran() {
    this(knuJNI.new_Denatran(), true);
  }

}
