/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class DetranSP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DetranSP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DetranSP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_DetranSP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.DetranSP_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.DetranSP_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.DetranSP_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.DetranSP_desc_erro_get(swigCPtr, this);
  }

  public void setPlaca(String value) {
    knuJNI.DetranSP_placa_set(swigCPtr, this, value);
  }

  public String getPlaca() {
    return knuJNI.DetranSP_placa_get(swigCPtr, this);
  }

  public void setRenavam(String value) {
    knuJNI.DetranSP_renavam_set(swigCPtr, this, value);
  }

  public String getRenavam() {
    return knuJNI.DetranSP_renavam_get(swigCPtr, this);
  }

  public void setIpva(String value) {
    knuJNI.DetranSP_ipva_set(swigCPtr, this, value);
  }

  public String getIpva() {
    return knuJNI.DetranSP_ipva_get(swigCPtr, this);
  }

  public void setTotal_multas(String value) {
    knuJNI.DetranSP_total_multas_set(swigCPtr, this, value);
  }

  public String getTotal_multas() {
    return knuJNI.DetranSP_total_multas_get(swigCPtr, this);
  }

  public void setBloqueio_furto(String value) {
    knuJNI.DetranSP_bloqueio_furto_set(swigCPtr, this, value);
  }

  public String getBloqueio_furto() {
    return knuJNI.DetranSP_bloqueio_furto_get(swigCPtr, this);
  }

  public void setRestricao_adm(String value) {
    knuJNI.DetranSP_restricao_adm_set(swigCPtr, this, value);
  }

  public String getRestricao_adm() {
    return knuJNI.DetranSP_restricao_adm_get(swigCPtr, this);
  }

  public void setRestricao_trib(String value) {
    knuJNI.DetranSP_restricao_trib_set(swigCPtr, this, value);
  }

  public String getRestricao_trib() {
    return knuJNI.DetranSP_restricao_trib_get(swigCPtr, this);
  }

  public void setRestricao_jud(String value) {
    knuJNI.DetranSP_restricao_jud_set(swigCPtr, this, value);
  }

  public String getRestricao_jud() {
    return knuJNI.DetranSP_restricao_jud_get(swigCPtr, this);
  }

  public void setRestricao_fin(String value) {
    knuJNI.DetranSP_restricao_fin_set(swigCPtr, this, value);
  }

  public String getRestricao_fin() {
    return knuJNI.DetranSP_restricao_fin_get(swigCPtr, this);
  }

  public void setRegistro_guincho(String value) {
    knuJNI.DetranSP_registro_guincho_set(swigCPtr, this, value);
  }

  public String getRegistro_guincho() {
    return knuJNI.DetranSP_registro_guincho_get(swigCPtr, this);
  }

  public void setInspecao_veicular(String value) {
    knuJNI.DetranSP_inspecao_veicular_set(swigCPtr, this, value);
  }

  public String getInspecao_veicular() {
    return knuJNI.DetranSP_inspecao_veicular_get(swigCPtr, this);
  }

  public void setLicenciamento(String value) {
    knuJNI.DetranSP_licenciamento_set(swigCPtr, this, value);
  }

  public String getLicenciamento() {
    return knuJNI.DetranSP_licenciamento_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.DetranSP_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.DetranSP_html_get(swigCPtr, this);
  }

  public DetranSP() {
    this(knuJNI.new_DetranSP(), true);
  }

}
