/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Fgts {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Fgts(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Fgts obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Fgts(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Fgts_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Fgts_cod_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.Fgts_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.Fgts_cnpj_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.Fgts_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.Fgts_data_consulta_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Fgts_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Fgts_desc_erro_get(swigCPtr, this);
  }

  public void setDesc_situacao(String value) {
    knuJNI.Fgts_desc_situacao_set(swigCPtr, this, value);
  }

  public String getDesc_situacao() {
    return knuJNI.Fgts_desc_situacao_get(swigCPtr, this);
  }

  public void setNome_fantasia(String value) {
    knuJNI.Fgts_nome_fantasia_set(swigCPtr, this, value);
  }

  public String getNome_fantasia() {
    return knuJNI.Fgts_nome_fantasia_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.Fgts_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.Fgts_razao_get(swigCPtr, this);
  }

  public void setSituacao(String value) {
    knuJNI.Fgts_situacao_set(swigCPtr, this, value);
  }

  public String getSituacao() {
    return knuJNI.Fgts_situacao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.Fgts_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.Fgts_html_get(swigCPtr, this);
  }

  public Fgts() {
    this(knuJNI.new_Fgts(), true);
  }

}
