/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class Ibge {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Ibge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ibge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_Ibge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.Ibge_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.Ibge_cod_erro_get(swigCPtr, this);
  }

  public void setArea(String value) {
    knuJNI.Ibge_area_set(swigCPtr, this, value);
  }

  public String getArea() {
    return knuJNI.Ibge_area_get(swigCPtr, this);
  }

  public void setCod_municipio(String value) {
    knuJNI.Ibge_cod_municipio_set(swigCPtr, this, value);
  }

  public String getCod_municipio() {
    return knuJNI.Ibge_cod_municipio_get(swigCPtr, this);
  }

  public void setCod_uf(String value) {
    knuJNI.Ibge_cod_uf_set(swigCPtr, this, value);
  }

  public String getCod_uf() {
    return knuJNI.Ibge_cod_uf_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.Ibge_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.Ibge_desc_erro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.Ibge_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.Ibge_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.Ibge_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.Ibge_uf_get(swigCPtr, this);
  }

  public Ibge() {
    this(knuJNI.new_Ibge(), true);
  }

}
