/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class IpvaSP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IpvaSP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IpvaSP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_IpvaSP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.IpvaSP_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.IpvaSP_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.IpvaSP_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.IpvaSP_desc_erro_get(swigCPtr, this);
  }

  public void setData_atualizacao(String value) {
    knuJNI.IpvaSP_data_atualizacao_set(swigCPtr, this, value);
  }

  public String getData_atualizacao() {
    return knuJNI.IpvaSP_data_atualizacao_get(swigCPtr, this);
  }

  public void setProprietario(String value) {
    knuJNI.IpvaSP_proprietario_set(swigCPtr, this, value);
  }

  public String getProprietario() {
    return knuJNI.IpvaSP_proprietario_get(swigCPtr, this);
  }

  public void setPlaca(String value) {
    knuJNI.IpvaSP_placa_set(swigCPtr, this, value);
  }

  public String getPlaca() {
    return knuJNI.IpvaSP_placa_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.IpvaSP_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.IpvaSP_municipio_get(swigCPtr, this);
  }

  public void setRenavam(String value) {
    knuJNI.IpvaSP_renavam_set(swigCPtr, this, value);
  }

  public String getRenavam() {
    return knuJNI.IpvaSP_renavam_get(swigCPtr, this);
  }

  public void setMarca_modelo(String value) {
    knuJNI.IpvaSP_marca_modelo_set(swigCPtr, this, value);
  }

  public String getMarca_modelo() {
    return knuJNI.IpvaSP_marca_modelo_get(swigCPtr, this);
  }

  public void setCod_ipva(String value) {
    knuJNI.IpvaSP_cod_ipva_set(swigCPtr, this, value);
  }

  public String getCod_ipva() {
    return knuJNI.IpvaSP_cod_ipva_get(swigCPtr, this);
  }

  public void setAno_fabricacao(String value) {
    knuJNI.IpvaSP_ano_fabricacao_set(swigCPtr, this, value);
  }

  public String getAno_fabricacao() {
    return knuJNI.IpvaSP_ano_fabricacao_get(swigCPtr, this);
  }

  public void setCombustivel(String value) {
    knuJNI.IpvaSP_combustivel_set(swigCPtr, this, value);
  }

  public String getCombustivel() {
    return knuJNI.IpvaSP_combustivel_get(swigCPtr, this);
  }

  public void setEspecie(String value) {
    knuJNI.IpvaSP_especie_set(swigCPtr, this, value);
  }

  public String getEspecie() {
    return knuJNI.IpvaSP_especie_get(swigCPtr, this);
  }

  public void setTipo(String value) {
    knuJNI.IpvaSP_tipo_set(swigCPtr, this, value);
  }

  public String getTipo() {
    return knuJNI.IpvaSP_tipo_get(swigCPtr, this);
  }

  public void setProcedencia(String value) {
    knuJNI.IpvaSP_procedencia_set(swigCPtr, this, value);
  }

  public String getProcedencia() {
    return knuJNI.IpvaSP_procedencia_get(swigCPtr, this);
  }

  public void setCategoria(String value) {
    knuJNI.IpvaSP_categoria_set(swigCPtr, this, value);
  }

  public String getCategoria() {
    return knuJNI.IpvaSP_categoria_get(swigCPtr, this);
  }

  public void setLiberado_licen(String value) {
    knuJNI.IpvaSP_liberado_licen_set(swigCPtr, this, value);
  }

  public String getLiberado_licen() {
    return knuJNI.IpvaSP_liberado_licen_get(swigCPtr, this);
  }

  public void setJa_licenciado(String value) {
    knuJNI.IpvaSP_ja_licenciado_set(swigCPtr, this, value);
  }

  public String getJa_licenciado() {
    return knuJNI.IpvaSP_ja_licenciado_get(swigCPtr, this);
  }

  public void setTotal_geral(String value) {
    knuJNI.IpvaSP_total_geral_set(swigCPtr, this, value);
  }

  public String getTotal_geral() {
    return knuJNI.IpvaSP_total_geral_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.IpvaSP_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.IpvaSP_html_get(swigCPtr, this);
  }

  public IpvaSP() {
    this(knuJNI.new_IpvaSP(), true);
  }

}
