/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class knu {
  public static ReceitaCPF receitaCPF(String cpf) {
    long cPtr = knuJNI.receitaCPF(cpf);
    return (cPtr == 0) ? null : new ReceitaCPF(cPtr, true);
  }

  public static ReceitaCNPJ receitaCNPJ(String cnpj) {
    long cPtr = knuJNI.receitaCNPJ(cnpj);
    return (cPtr == 0) ? null : new ReceitaCNPJ(cPtr, true);
  }

  public static Anvisa anvisaCNPJ(String cnpj) {
    long cPtr = knuJNI.anvisaCNPJ(cnpj);
    return (cPtr == 0) ? null : new Anvisa(cPtr, true);
  }

  public static Fgts fgtsCNPJ(String cnpj) {
    long cPtr = knuJNI.fgtsCNPJ(cnpj);
    return (cPtr == 0) ? null : new Fgts(cPtr, true);
  }

  public static Ibge ibgeCodigo(String codigo) {
    long cPtr = knuJNI.ibgeCodigo(codigo);
    return (cPtr == 0) ? null : new Ibge(cPtr, true);
  }

  public static Ibge ibgeMunicipio(String municipio) {
    long cPtr = knuJNI.ibgeMunicipio(municipio);
    return (cPtr == 0) ? null : new Ibge(cPtr, true);
  }

  public static Correios consultarEndereco(String cepOuRua) {
    long cPtr = knuJNI.consultarEndereco(cepOuRua);
    return (cPtr == 0) ? null : new Correios(cPtr, true);
  }

  public static ReceitaCNDIR receitaCNDIR(String cnpj) {
    long cPtr = knuJNI.receitaCNDIR(cnpj);
    return (cPtr == 0) ? null : new ReceitaCNDIR(cPtr, true);
  }

  public static ReceitaCCD receitaCCD(String cnpj) {
    long cPtr = knuJNI.receitaCCD(cnpj);
    return (cPtr == 0) ? null : new ReceitaCCD(cPtr, true);
  }

  public static ReceitaCCD receitaCCDCPF(String cpf) {
    long cPtr = knuJNI.receitaCCDCPF(cpf);
    return (cPtr == 0) ? null : new ReceitaCCD(cPtr, true);
  }

  public static ReceitaSimples receitaSimples(String cnpj) {
    long cPtr = knuJNI.receitaSimples(cnpj);
    return (cPtr == 0) ? null : new ReceitaSimples(cPtr, true);
  }

  public static ReceitaQSA receitaQSA(String cnpj) {
    long cPtr = knuJNI.receitaQSA(cnpj);
    return (cPtr == 0) ? null : new ReceitaQSA(cPtr, true);
  }

  public static Cadesp cadespCNPJ(String cnpj) {
    long cPtr = knuJNI.cadespCNPJ(cnpj);
    return (cPtr == 0) ? null : new Cadesp(cPtr, true);
  }

  public static Cadesp cadespIE(String ie) {
    long cPtr = knuJNI.cadespIE(ie);
    return (cPtr == 0) ? null : new Cadesp(cPtr, true);
  }

  public static Denatran denatran(String renavam, String cpf_cnpj) {
    long cPtr = knuJNI.denatran(renavam, cpf_cnpj);
    return (cPtr == 0) ? null : new Denatran(cPtr, true);
  }

  public static Cnh validacaoCnh(String cpf, String numero_registro, String numero_seguranca) {
    long cPtr = knuJNI.validacaoCnh(cpf, numero_registro, numero_seguranca);
    return (cPtr == 0) ? null : new Cnh(cPtr, true);
  }

  public static DetranSP detranSP(String placa, String renavam) {
    long cPtr = knuJNI.detranSP(placa, renavam);
    return (cPtr == 0) ? null : new DetranSP(cPtr, true);
  }

  public static IpvaSP ipvaSP(String renavam, String cpf_cnpj) {
    long cPtr = knuJNI.ipvaSP(renavam, cpf_cnpj);
    return (cPtr == 0) ? null : new IpvaSP(cPtr, true);
  }

  public static Nfe consultarNfeHtml(String chave) {
    long cPtr = knuJNI.consultarNfeHtml(chave);
    return (cPtr == 0) ? null : new Nfe(cPtr, true);
  }

  public static Nfe consultarNfeXml(String chave, String cert_path, String cert_pass, String cert_type) {
    long cPtr = knuJNI.consultarNfeXml(chave, cert_path, cert_pass, cert_type);
    return (cPtr == 0) ? null : new Nfe(cPtr, true);
  }

  public static Cte consultarCteHtml(String chave) {
    long cPtr = knuJNI.consultarCteHtml(chave);
    return (cPtr == 0) ? null : new Cte(cPtr, true);
  }

  public static Cte consultarCteXml(String chave, String cert_path, String cert_pass, String cert_type) {
    long cPtr = knuJNI.consultarCteXml(chave, cert_path, cert_pass, cert_type);
    return (cPtr == 0) ? null : new Cte(cPtr, true);
  }

  public static SintegraAC sintegraAC_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraAC_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraAC(cPtr, true);
  }

  public static SintegraAC sintegraAC_CPF(String cpf) {
    long cPtr = knuJNI.sintegraAC_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraAC(cPtr, true);
  }

  public static SintegraAC sintegraAC_IE(String ie) {
    long cPtr = knuJNI.sintegraAC_IE(ie);
    return (cPtr == 0) ? null : new SintegraAC(cPtr, true);
  }

  public static SintegraAL sintegraAL_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraAL_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraAL(cPtr, true);
  }

  public static SintegraAL sintegraAL_IE(String ie) {
    long cPtr = knuJNI.sintegraAL_IE(ie);
    return (cPtr == 0) ? null : new SintegraAL(cPtr, true);
  }

  public static SintegraAM sintegraAM_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraAM_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraAM(cPtr, true);
  }

  public static SintegraAP sintegraAP_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraAP_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraAP(cPtr, true);
  }

  public static SintegraAP sintegraAP_IE(String ie) {
    long cPtr = knuJNI.sintegraAP_IE(ie);
    return (cPtr == 0) ? null : new SintegraAP(cPtr, true);
  }

  public static SintegraBA sintegraBA_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraBA_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraBA(cPtr, true);
  }

  public static SintegraBA sintegraBA_IE(String ie) {
    long cPtr = knuJNI.sintegraBA_IE(ie);
    return (cPtr == 0) ? null : new SintegraBA(cPtr, true);
  }

  public static SintegraCE sintegraCE_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraCE_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraCE(cPtr, true);
  }

  public static SintegraCE sintegraCE_IE(String ie) {
    long cPtr = knuJNI.sintegraCE_IE(ie);
    return (cPtr == 0) ? null : new SintegraCE(cPtr, true);
  }

  public static SintegraDF sintegraDF_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraDF_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraDF(cPtr, true);
  }

  public static SintegraDF sintegraDF_CPF(String cpf) {
    long cPtr = knuJNI.sintegraDF_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraDF(cPtr, true);
  }

  public static SintegraDF sintegraDF_CF(String cf) {
    long cPtr = knuJNI.sintegraDF_CF(cf);
    return (cPtr == 0) ? null : new SintegraDF(cPtr, true);
  }

  public static SintegraES sintegraES_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraES_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraES(cPtr, true);
  }

  public static SintegraES sintegraES_IE(String ie) {
    long cPtr = knuJNI.sintegraES_IE(ie);
    return (cPtr == 0) ? null : new SintegraES(cPtr, true);
  }

  public static SintegraGO sintegraGO_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraGO_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraGO(cPtr, true);
  }

  public static SintegraGO sintegraGO_IE(String ie) {
    long cPtr = knuJNI.sintegraGO_IE(ie);
    return (cPtr == 0) ? null : new SintegraGO(cPtr, true);
  }

  public static SintegraGO sintegraGO_CPF(String cpf) {
    long cPtr = knuJNI.sintegraGO_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraGO(cPtr, true);
  }

  public static SintegraMA sintegraMA_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraMA_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraMA(cPtr, true);
  }

  public static SintegraMA sintegraMA_CPF(String cpf) {
    long cPtr = knuJNI.sintegraMA_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraMA(cPtr, true);
  }

  public static SintegraMA sintegraMA_IE(String ie) {
    long cPtr = knuJNI.sintegraMA_IE(ie);
    return (cPtr == 0) ? null : new SintegraMA(cPtr, true);
  }

  public static SintegraMG sintegraMG_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraMG_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraMG(cPtr, true);
  }

  public static SintegraMG sintegraMG_IE(String ie) {
    long cPtr = knuJNI.sintegraMG_IE(ie);
    return (cPtr == 0) ? null : new SintegraMG(cPtr, true);
  }

  public static SintegraMS sintegraMS_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraMS_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraMS(cPtr, true);
  }

  public static SintegraMS sintegraMS_IE(String ie) {
    long cPtr = knuJNI.sintegraMS_IE(ie);
    return (cPtr == 0) ? null : new SintegraMS(cPtr, true);
  }

  public static SintegraMT sintegraMT_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraMT_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraMT(cPtr, true);
  }

  public static SintegraMT sintegraMT_IE(String ie) {
    long cPtr = knuJNI.sintegraMT_IE(ie);
    return (cPtr == 0) ? null : new SintegraMT(cPtr, true);
  }

  public static SintegraPA sintegraPA_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraPA_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraPA(cPtr, true);
  }

  public static SintegraPA sintegraPA_CPF(String cpf) {
    long cPtr = knuJNI.sintegraPA_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraPA(cPtr, true);
  }

  public static SintegraPA sintegraPA_IE(String ie) {
    long cPtr = knuJNI.sintegraPA_IE(ie);
    return (cPtr == 0) ? null : new SintegraPA(cPtr, true);
  }

  public static SintegraPE sintegraPE_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraPE_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraPE(cPtr, true);
  }

  public static SintegraPE sintegraPE_CPF(String cpf) {
    long cPtr = knuJNI.sintegraPE_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraPE(cPtr, true);
  }

  public static SintegraPE sintegraPE_IE(String ie) {
    long cPtr = knuJNI.sintegraPE_IE(ie);
    return (cPtr == 0) ? null : new SintegraPE(cPtr, true);
  }

  public static SintegraPI sintegraPI_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraPI_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraPI(cPtr, true);
  }

  public static SintegraPI sintegraPI_CPF(String cpf) {
    long cPtr = knuJNI.sintegraPI_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraPI(cPtr, true);
  }

  public static SintegraPI sintegraPI_IE(String ie) {
    long cPtr = knuJNI.sintegraPI_IE(ie);
    return (cPtr == 0) ? null : new SintegraPI(cPtr, true);
  }

  public static SintegraRJ sintegraRJ_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraRJ_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraRJ(cPtr, true);
  }

  public static SintegraRJ sintegraRJ_CPF(String cpf) {
    long cPtr = knuJNI.sintegraRJ_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraRJ(cPtr, true);
  }

  public static SintegraRJ sintegraRJ_IE(String ie) {
    long cPtr = knuJNI.sintegraRJ_IE(ie);
    return (cPtr == 0) ? null : new SintegraRJ(cPtr, true);
  }

  public static SintegraRN sintegraRN_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraRN_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraRN(cPtr, true);
  }

  public static SintegraRN sintegraRN_IE(String ie) {
    long cPtr = knuJNI.sintegraRN_IE(ie);
    return (cPtr == 0) ? null : new SintegraRN(cPtr, true);
  }

  public static SintegraRR sintegraRR_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraRR_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraRR(cPtr, true);
  }

  public static SintegraRR sintegraRR_IE(String ie) {
    long cPtr = knuJNI.sintegraRR_IE(ie);
    return (cPtr == 0) ? null : new SintegraRR(cPtr, true);
  }

  public static SintegraSE sintegraSE_CNPJ_CPF(String cnpj) {
    long cPtr = knuJNI.sintegraSE_CNPJ_CPF(cnpj);
    return (cPtr == 0) ? null : new SintegraSE(cPtr, true);
  }

  public static SintegraSE sintegraSE_IE(String ie) {
    long cPtr = knuJNI.sintegraSE_IE(ie);
    return (cPtr == 0) ? null : new SintegraSE(cPtr, true);
  }

  public static SintegraSP sintegraSP_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraSP_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraSP(cPtr, true);
  }

  public static SintegraSP sintegraSP_IE(String ie) {
    long cPtr = knuJNI.sintegraSP_IE(ie);
    return (cPtr == 0) ? null : new SintegraSP(cPtr, true);
  }

  public static SintegraSU sintegraSU(String inscricao) {
    long cPtr = knuJNI.sintegraSU(inscricao);
    return (cPtr == 0) ? null : new SintegraSU(cPtr, true);
  }

  public static SintegraPB sintegraPB_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraPB_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraPB(cPtr, true);
  }

  public static SintegraPB sintegraPB_IE(String ie) {
    long cPtr = knuJNI.sintegraPB_IE(ie);
    return (cPtr == 0) ? null : new SintegraPB(cPtr, true);
  }

  public static SintegraTO sintegraTO_CNPJ(String cnpj) {
    long cPtr = knuJNI.sintegraTO_CNPJ(cnpj);
    return (cPtr == 0) ? null : new SintegraTO(cPtr, true);
  }

  public static SintegraTO sintegraTO_CPF(String cpf) {
    long cPtr = knuJNI.sintegraTO_CPF(cpf);
    return (cPtr == 0) ? null : new SintegraTO(cPtr, true);
  }

  public static SintegraTO sintegraTO_IE(String ie) {
    long cPtr = knuJNI.sintegraTO_IE(ie);
    return (cPtr == 0) ? null : new SintegraTO(cPtr, true);
  }

  public static void ativarLog(String arquivo) {
    knuJNI.ativarLog(arquivo);
  }

  public static int verCreditos() {
    return knuJNI.verCreditos();
  }

  public static void usarProxy(String str, int tipo) {
    knuJNI.usarProxy(str, tipo);
  }

  public static void naoUsarProxy() {
    knuJNI.naoUsarProxy();
  }

  public static String getVersao() {
    return knuJNI.versao_get();
  }

}
