/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class ReceitaQSA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReceitaQSA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReceitaQSA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_ReceitaQSA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.ReceitaQSA_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.ReceitaQSA_cod_erro_get(swigCPtr, this);
  }

  public void setQnt_socios(int value) {
    knuJNI.ReceitaQSA_qnt_socios_set(swigCPtr, this, value);
  }

  public int getQnt_socios() {
    return knuJNI.ReceitaQSA_qnt_socios_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.ReceitaQSA_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.ReceitaQSA_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.ReceitaQSA_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.ReceitaQSA_cnpj_get(swigCPtr, this);
  }

  public void setNome_empresarial(String value) {
    knuJNI.ReceitaQSA_nome_empresarial_set(swigCPtr, this, value);
  }

  public String getNome_empresarial() {
    return knuJNI.ReceitaQSA_nome_empresarial_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.ReceitaQSA_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.ReceitaQSA_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.ReceitaQSA_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.ReceitaQSA_html_get(swigCPtr, this);
  }

  public String getSocioCpfCnpj(int index) {
    return knuJNI.ReceitaQSA_getSocioCpfCnpj(swigCPtr, this, index);
  }

  public String getSocioEntradaSociedade(int index) {
    return knuJNI.ReceitaQSA_getSocioEntradaSociedade(swigCPtr, this, index);
  }

  public String getSocioNome(int index) {
    return knuJNI.ReceitaQSA_getSocioNome(swigCPtr, this, index);
  }

  public String getSocioQualificacao(int index) {
    return knuJNI.ReceitaQSA_getSocioQualificacao(swigCPtr, this, index);
  }

  public String getSocioPartCapitalSocial(int index) {
    return knuJNI.ReceitaQSA_getSocioPartCapitalSocial(swigCPtr, this, index);
  }

  public ReceitaQSA() {
    this(knuJNI.new_ReceitaQSA(), true);
  }

}
