/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class ReceitaCNDIR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReceitaCNDIR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReceitaCNDIR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_ReceitaCNDIR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.ReceitaCNDIR_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.ReceitaCNDIR_cod_erro_get(swigCPtr, this);
  }

  public void setArea(String value) {
    knuJNI.ReceitaCNDIR_area_set(swigCPtr, this, value);
  }

  public String getArea() {
    return knuJNI.ReceitaCNDIR_area_get(swigCPtr, this);
  }

  public void setContribuinte(String value) {
    knuJNI.ReceitaCNDIR_contribuinte_set(swigCPtr, this, value);
  }

  public String getContribuinte() {
    return knuJNI.ReceitaCNDIR_contribuinte_get(swigCPtr, this);
  }

  public void setCpf(String value) {
    knuJNI.ReceitaCNDIR_cpf_set(swigCPtr, this, value);
  }

  public String getCpf() {
    return knuJNI.ReceitaCNDIR_cpf_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.ReceitaCNDIR_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.ReceitaCNDIR_desc_erro_get(swigCPtr, this);
  }

  public void setDescricao(String value) {
    knuJNI.ReceitaCNDIR_descricao_set(swigCPtr, this, value);
  }

  public String getDescricao() {
    return knuJNI.ReceitaCNDIR_descricao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.ReceitaCNDIR_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.ReceitaCNDIR_html_get(swigCPtr, this);
  }

  public void setInfo(String value) {
    knuJNI.ReceitaCNDIR_info_set(swigCPtr, this, value);
  }

  public String getInfo() {
    return knuJNI.ReceitaCNDIR_info_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.ReceitaCNDIR_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.ReceitaCNDIR_municipio_get(swigCPtr, this);
  }

  public void setNirf(String value) {
    knuJNI.ReceitaCNDIR_nirf_set(swigCPtr, this, value);
  }

  public String getNirf() {
    return knuJNI.ReceitaCNDIR_nirf_get(swigCPtr, this);
  }

  public void setNome_imovel(String value) {
    knuJNI.ReceitaCNDIR_nome_imovel_set(swigCPtr, this, value);
  }

  public String getNome_imovel() {
    return knuJNI.ReceitaCNDIR_nome_imovel_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.ReceitaCNDIR_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.ReceitaCNDIR_uf_get(swigCPtr, this);
  }

  public ReceitaCNDIR() {
    this(knuJNI.new_ReceitaCNDIR(), true);
  }

}
