/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraAM {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraAM(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraAM obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraAM(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraAM_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraAM_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraAM_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraAM_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraAM_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraAM_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraAM_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraAM_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraAM_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraAM_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraAM_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraAM_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraAM_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraAM_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraAM_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraAM_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraAM_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraAM_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraAM_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraAM_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraAM_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraAM_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraAM_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraAM_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraAM_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraAM_telefone_get(swigCPtr, this);
  }

  public void setCnae_principal(String value) {
    knuJNI.SintegraAM_cnae_principal_set(swigCPtr, this, value);
  }

  public String getCnae_principal() {
    return knuJNI.SintegraAM_cnae_principal_get(swigCPtr, this);
  }

  public void setCnae_secundario(String value) {
    knuJNI.SintegraAM_cnae_secundario_set(swigCPtr, this, value);
  }

  public String getCnae_secundario() {
    return knuJNI.SintegraAM_cnae_secundario_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraAM_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraAM_situacao_cadastral_get(swigCPtr, this);
  }

  public void setInicio_atividades(String value) {
    knuJNI.SintegraAM_inicio_atividades_set(swigCPtr, this, value);
  }

  public String getInicio_atividades() {
    return knuJNI.SintegraAM_inicio_atividades_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraAM_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraAM_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraAM_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraAM_html_get(swigCPtr, this);
  }

  public SintegraAM() {
    this(knuJNI.new_SintegraAM(), true);
  }

}
