/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraMG {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraMG(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraMG obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraMG(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraMG_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraMG_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraMG_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraMG_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraMG_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraMG_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraMG_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraMG_ie_get(swigCPtr, this);
  }

  public void setUf_identificacao(String value) {
    knuJNI.SintegraMG_uf_identificacao_set(swigCPtr, this, value);
  }

  public String getUf_identificacao() {
    return knuJNI.SintegraMG_uf_identificacao_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraMG_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraMG_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraMG_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraMG_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraMG_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraMG_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraMG_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraMG_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraMG_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraMG_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraMG_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraMG_municipio_get(swigCPtr, this);
  }

  public void setUf_endereco(String value) {
    knuJNI.SintegraMG_uf_endereco_set(swigCPtr, this, value);
  }

  public String getUf_endereco() {
    return knuJNI.SintegraMG_uf_endereco_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraMG_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraMG_cep_get(swigCPtr, this);
  }

  public void setDistrito(String value) {
    knuJNI.SintegraMG_distrito_set(swigCPtr, this, value);
  }

  public String getDistrito() {
    return knuJNI.SintegraMG_distrito_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraMG_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraMG_telefone_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraMG_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraMG_atividade_economica_get(swigCPtr, this);
  }

  public void setData_ie(String value) {
    knuJNI.SintegraMG_data_ie_set(swigCPtr, this, value);
  }

  public String getData_ie() {
    return knuJNI.SintegraMG_data_ie_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraMG_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraMG_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraMG_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraMG_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraMG_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraMG_regime_get(swigCPtr, this);
  }

  public void setObservacoes(String value) {
    knuJNI.SintegraMG_observacoes_set(swigCPtr, this, value);
  }

  public String getObservacoes() {
    return knuJNI.SintegraMG_observacoes_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraMG_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraMG_data_consulta_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraMG_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraMG_numero_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraMG_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraMG_html_get(swigCPtr, this);
  }

  public SintegraMG() {
    this(knuJNI.new_SintegraMG(), true);
  }

}
