/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraSP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraSP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraSP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraSP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraSP_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraSP_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraSP_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraSP_desc_erro_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraSP_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraSP_ie_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraSP_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraSP_cnpj_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraSP_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraSP_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraSP_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraSP_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraSP_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraSP_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraSP_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraSP_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraSP_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraSP_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraSP_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraSP_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraSP_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraSP_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraSP_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraSP_cep_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraSP_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraSP_atividade_economica_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraSP_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraSP_situacao_cadastral_get(swigCPtr, this);
  }

  public void setStatus(String value) {
    knuJNI.SintegraSP_status_set(swigCPtr, this, value);
  }

  public String getStatus() {
    return knuJNI.SintegraSP_status_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraSP_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraSP_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraSP_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraSP_regime_get(swigCPtr, this);
  }

  public void setData_credenciamento(String value) {
    knuJNI.SintegraSP_data_credenciamento_set(swigCPtr, this, value);
  }

  public String getData_credenciamento() {
    return knuJNI.SintegraSP_data_credenciamento_get(swigCPtr, this);
  }

  public void setIndicador_obrigatoriedade(String value) {
    knuJNI.SintegraSP_indicador_obrigatoriedade_set(swigCPtr, this, value);
  }

  public String getIndicador_obrigatoriedade() {
    return knuJNI.SintegraSP_indicador_obrigatoriedade_get(swigCPtr, this);
  }

  public void setData_obrigatoriedade(String value) {
    knuJNI.SintegraSP_data_obrigatoriedade_set(swigCPtr, this, value);
  }

  public String getData_obrigatoriedade() {
    return knuJNI.SintegraSP_data_obrigatoriedade_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraSP_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraSP_data_consulta_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraSP_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraSP_numero_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraSP_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraSP_html_get(swigCPtr, this);
  }

  public SintegraSP() {
    this(knuJNI.new_SintegraSP(), true);
  }

}
