/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraPE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraPE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraPE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraPE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraPE_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraPE_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraPE_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraPE_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj_cpf(String value) {
    knuJNI.SintegraPE_cnpj_cpf_set(swigCPtr, this, value);
  }

  public String getCnpj_cpf() {
    return knuJNI.SintegraPE_cnpj_cpf_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraPE_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraPE_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraPE_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraPE_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraPE_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraPE_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraPE_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraPE_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraPE_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraPE_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraPE_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraPE_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraPE_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraPE_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraPE_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraPE_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraPE_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraPE_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraPE_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraPE_telefone_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraPE_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraPE_regime_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraPE_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraPE_atividade_economica_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraPE_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraPE_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesde(String value) {
    knuJNI.SintegraPE_desde_set(swigCPtr, this, value);
  }

  public String getDesde() {
    return knuJNI.SintegraPE_desde_get(swigCPtr, this);
  }

  public void setData_inscricao(String value) {
    knuJNI.SintegraPE_data_inscricao_set(swigCPtr, this, value);
  }

  public String getData_inscricao() {
    return knuJNI.SintegraPE_data_inscricao_get(swigCPtr, this);
  }

  public void setCredenciamento_antecipado(String value) {
    knuJNI.SintegraPE_credenciamento_antecipado_set(swigCPtr, this, value);
  }

  public String getCredenciamento_antecipado() {
    return knuJNI.SintegraPE_credenciamento_antecipado_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraPE_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraPE_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraPE_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraPE_html_get(swigCPtr, this);
  }

  public SintegraPE() {
    this(knuJNI.new_SintegraPE(), true);
  }

}
