/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraMA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraMA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraMA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraMA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraMA_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraMA_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraMA_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraMA_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraMA_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraMA_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraMA_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraMA_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraMA_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraMA_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraMA_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraMA_regime_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraMA_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraMA_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraMA_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraMA_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraMA_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraMA_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraMA_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraMA_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraMA_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraMA_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraMA_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraMA_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraMA_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraMA_cep_get(swigCPtr, this);
  }

  public void setDdd(String value) {
    knuJNI.SintegraMA_ddd_set(swigCPtr, this, value);
  }

  public String getDdd() {
    return knuJNI.SintegraMA_ddd_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraMA_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraMA_telefone_get(swigCPtr, this);
  }

  public void setCnae_principal(String value) {
    knuJNI.SintegraMA_cnae_principal_set(swigCPtr, this, value);
  }

  public String getCnae_principal() {
    return knuJNI.SintegraMA_cnae_principal_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraMA_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraMA_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraMA_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraMA_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setObrigado_nfe_apartir(String value) {
    knuJNI.SintegraMA_obrigado_nfe_apartir_set(swigCPtr, this, value);
  }

  public String getObrigado_nfe_apartir() {
    return knuJNI.SintegraMA_obrigado_nfe_apartir_get(swigCPtr, this);
  }

  public void setObrigado_efd_apartir(String value) {
    knuJNI.SintegraMA_obrigado_efd_apartir_set(swigCPtr, this, value);
  }

  public String getObrigado_efd_apartir() {
    return knuJNI.SintegraMA_obrigado_efd_apartir_get(swigCPtr, this);
  }

  public void setObrigado_cte_apartir(String value) {
    knuJNI.SintegraMA_obrigado_cte_apartir_set(swigCPtr, this, value);
  }

  public String getObrigado_cte_apartir() {
    return knuJNI.SintegraMA_obrigado_cte_apartir_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraMA_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraMA_data_consulta_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraMA_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraMA_numero_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraMA_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraMA_html_get(swigCPtr, this);
  }

  public SintegraMA() {
    this(knuJNI.new_SintegraMA(), true);
  }

}
