/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraDF {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraDF(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraDF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraDF(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraDF_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraDF_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_principal(String value) {
    knuJNI.SintegraDF_atividade_principal_set(swigCPtr, this, value);
  }

  public String getAtividade_principal() {
    return knuJNI.SintegraDF_atividade_principal_get(swigCPtr, this);
  }

  public void setAtividade_secundaria(String value) {
    knuJNI.SintegraDF_atividade_secundaria_set(swigCPtr, this, value);
  }

  public String getAtividade_secundaria() {
    return knuJNI.SintegraDF_atividade_secundaria_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraDF_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraDF_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraDF_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraDF_cep_get(swigCPtr, this);
  }

  public void setCf(String value) {
    knuJNI.SintegraDF_cf_set(swigCPtr, this, value);
  }

  public String getCf() {
    return knuJNI.SintegraDF_cf_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraDF_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraDF_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraDF_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraDF_complemento_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraDF_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraDF_data_consulta_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraDF_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraDF_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraDF_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraDF_desc_erro_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraDF_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraDF_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraDF_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraDF_municipio_get(swigCPtr, this);
  }

  public void setNome_fantasia(String value) {
    knuJNI.SintegraDF_nome_fantasia_set(swigCPtr, this, value);
  }

  public String getNome_fantasia() {
    return knuJNI.SintegraDF_nome_fantasia_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraDF_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraDF_numero_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraDF_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraDF_numero_consulta_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraDF_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraDF_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraDF_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraDF_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraDF_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraDF_situacao_cadastral_get(swigCPtr, this);
  }

  public void setSituacao_sintegra(String value) {
    knuJNI.SintegraDF_situacao_sintegra_set(swigCPtr, this, value);
  }

  public String getSituacao_sintegra() {
    return knuJNI.SintegraDF_situacao_sintegra_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraDF_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraDF_telefone_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraDF_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraDF_uf_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraDF_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraDF_html_get(swigCPtr, this);
  }

  public SintegraDF() {
    this(knuJNI.new_SintegraDF(), true);
  }

}
