/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraES {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraES_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraES_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraES_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraES_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraES_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraES_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraES_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraES_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraES_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraES_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraES_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraES_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraES_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraES_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraES_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraES_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraES_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraES_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraES_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraES_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraES_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraES_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraES_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraES_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraES_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraES_telefone_get(swigCPtr, this);
  }

  public void setAtividade_principal(String value) {
    knuJNI.SintegraES_atividade_principal_set(swigCPtr, this, value);
  }

  public String getAtividade_principal() {
    return knuJNI.SintegraES_atividade_principal_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraES_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraES_regime_get(swigCPtr, this);
  }

  public void setData_inicio(String value) {
    knuJNI.SintegraES_data_inicio_set(swigCPtr, this, value);
  }

  public String getData_inicio() {
    return knuJNI.SintegraES_data_inicio_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraES_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraES_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraES_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraES_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraES_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraES_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraES_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraES_html_get(swigCPtr, this);
  }

  public SintegraES() {
    this(knuJNI.new_SintegraES(), true);
  }

}
