/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraRR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraRR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraRR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraRR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraRR_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraRR_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraRR_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraRR_atividade_economica_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraRR_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraRR_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraRR_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraRR_cep_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraRR_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraRR_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraRR_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraRR_complemento_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraRR_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraRR_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraRR_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraRR_desc_erro_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraRR_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraRR_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraRR_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraRR_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraRR_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraRR_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraRR_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraRR_numero_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraRR_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraRR_razao_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraRR_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraRR_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraRR_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraRR_telefone_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraRR_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraRR_uf_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraRR_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraRR_html_get(swigCPtr, this);
  }

  public SintegraRR() {
    this(knuJNI.new_SintegraRR(), true);
  }

}
