/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraRJ {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraRJ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraRJ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraRJ(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraRJ_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraRJ_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraRJ_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraRJ_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraRJ_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraRJ_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraRJ_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraRJ_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraRJ_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraRJ_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraRJ_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraRJ_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraRJ_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraRJ_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraRJ_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraRJ_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraRJ_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraRJ_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraRJ_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraRJ_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraRJ_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraRJ_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraRJ_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraRJ_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraRJ_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraRJ_telefone_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraRJ_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraRJ_atividade_economica_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraRJ_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraRJ_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraRJ_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraRJ_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_concessao(String value) {
    knuJNI.SintegraRJ_data_concessao_set(swigCPtr, this, value);
  }

  public String getData_concessao() {
    return knuJNI.SintegraRJ_data_concessao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraRJ_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraRJ_regime_get(swigCPtr, this);
  }

  public void setObservacao(String value) {
    knuJNI.SintegraRJ_observacao_set(swigCPtr, this, value);
  }

  public String getObservacao() {
    return knuJNI.SintegraRJ_observacao_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraRJ_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraRJ_data_consulta_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraRJ_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraRJ_numero_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraRJ_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraRJ_html_get(swigCPtr, this);
  }

  public SintegraRJ() {
    this(knuJNI.new_SintegraRJ(), true);
  }

}
