/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraCE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraCE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraCE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraCE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraCE_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraCE_cod_erro_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraCE_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraCE_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraCE_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraCE_cep_get(swigCPtr, this);
  }

  public void setCnae_primario(String value) {
    knuJNI.SintegraCE_cnae_primario_set(swigCPtr, this, value);
  }

  public String getCnae_primario() {
    return knuJNI.SintegraCE_cnae_primario_get(swigCPtr, this);
  }

  public void setCnae_secundario(String value) {
    knuJNI.SintegraCE_cnae_secundario_set(swigCPtr, this, value);
  }

  public String getCnae_secundario() {
    return knuJNI.SintegraCE_cnae_secundario_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraCE_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraCE_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraCE_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraCE_complemento_get(swigCPtr, this);
  }

  public void setCredenciamento(String value) {
    knuJNI.SintegraCE_credenciamento_set(swigCPtr, this, value);
  }

  public String getCredenciamento() {
    return knuJNI.SintegraCE_credenciamento_get(swigCPtr, this);
  }

  public void setData_atividade(String value) {
    knuJNI.SintegraCE_data_atividade_set(swigCPtr, this, value);
  }

  public String getData_atividade() {
    return knuJNI.SintegraCE_data_atividade_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraCE_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraCE_data_consulta_get(swigCPtr, this);
  }

  public void setData_obrigatoriedade_efd(String value) {
    knuJNI.SintegraCE_data_obrigatoriedade_efd_set(swigCPtr, this, value);
  }

  public String getData_obrigatoriedade_efd() {
    return knuJNI.SintegraCE_data_obrigatoriedade_efd_get(swigCPtr, this);
  }

  public void setData_obrigatoriedade_nfe(String value) {
    knuJNI.SintegraCE_data_obrigatoriedade_nfe_set(swigCPtr, this, value);
  }

  public String getData_obrigatoriedade_nfe() {
    return knuJNI.SintegraCE_data_obrigatoriedade_nfe_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraCE_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraCE_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraCE_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraCE_desc_erro_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraCE_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraCE_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraCE_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraCE_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraCE_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraCE_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraCE_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraCE_numero_get(swigCPtr, this);
  }

  public void setObrigado_efd(String value) {
    knuJNI.SintegraCE_obrigado_efd_set(swigCPtr, this, value);
  }

  public String getObrigado_efd() {
    return knuJNI.SintegraCE_obrigado_efd_get(swigCPtr, this);
  }

  public void setObrigado_nfe(String value) {
    knuJNI.SintegraCE_obrigado_nfe_set(swigCPtr, this, value);
  }

  public String getObrigado_nfe() {
    return knuJNI.SintegraCE_obrigado_nfe_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraCE_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraCE_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraCE_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraCE_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraCE_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraCE_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraCE_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraCE_telefone_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraCE_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraCE_uf_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraCE_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraCE_html_get(swigCPtr, this);
  }

  public SintegraCE() {
    this(knuJNI.new_SintegraCE(), true);
  }

}
