/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraRN {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraRN(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraRN obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraRN(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraRN_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraRN_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraRN_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraRN_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraRN_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraRN_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraRN_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraRN_ie_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraRN_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraRN_razao_get(swigCPtr, this);
  }

  public void setLogradouro_estab(String value) {
    knuJNI.SintegraRN_logradouro_estab_set(swigCPtr, this, value);
  }

  public String getLogradouro_estab() {
    return knuJNI.SintegraRN_logradouro_estab_get(swigCPtr, this);
  }

  public void setNumero_estab(String value) {
    knuJNI.SintegraRN_numero_estab_set(swigCPtr, this, value);
  }

  public String getNumero_estab() {
    return knuJNI.SintegraRN_numero_estab_get(swigCPtr, this);
  }

  public void setComplemento_estab(String value) {
    knuJNI.SintegraRN_complemento_estab_set(swigCPtr, this, value);
  }

  public String getComplemento_estab() {
    return knuJNI.SintegraRN_complemento_estab_get(swigCPtr, this);
  }

  public void setBairro_estab(String value) {
    knuJNI.SintegraRN_bairro_estab_set(swigCPtr, this, value);
  }

  public String getBairro_estab() {
    return knuJNI.SintegraRN_bairro_estab_get(swigCPtr, this);
  }

  public void setMunicipio_estab(String value) {
    knuJNI.SintegraRN_municipio_estab_set(swigCPtr, this, value);
  }

  public String getMunicipio_estab() {
    return knuJNI.SintegraRN_municipio_estab_get(swigCPtr, this);
  }

  public void setUf_estab(String value) {
    knuJNI.SintegraRN_uf_estab_set(swigCPtr, this, value);
  }

  public String getUf_estab() {
    return knuJNI.SintegraRN_uf_estab_get(swigCPtr, this);
  }

  public void setCep_estab(String value) {
    knuJNI.SintegraRN_cep_estab_set(swigCPtr, this, value);
  }

  public String getCep_estab() {
    return knuJNI.SintegraRN_cep_estab_get(swigCPtr, this);
  }

  public void setTelefone_estab(String value) {
    knuJNI.SintegraRN_telefone_estab_set(swigCPtr, this, value);
  }

  public String getTelefone_estab() {
    return knuJNI.SintegraRN_telefone_estab_get(swigCPtr, this);
  }

  public void setLogradouro_corresp(String value) {
    knuJNI.SintegraRN_logradouro_corresp_set(swigCPtr, this, value);
  }

  public String getLogradouro_corresp() {
    return knuJNI.SintegraRN_logradouro_corresp_get(swigCPtr, this);
  }

  public void setNumero_corresp(String value) {
    knuJNI.SintegraRN_numero_corresp_set(swigCPtr, this, value);
  }

  public String getNumero_corresp() {
    return knuJNI.SintegraRN_numero_corresp_get(swigCPtr, this);
  }

  public void setComplemento_corresp(String value) {
    knuJNI.SintegraRN_complemento_corresp_set(swigCPtr, this, value);
  }

  public String getComplemento_corresp() {
    return knuJNI.SintegraRN_complemento_corresp_get(swigCPtr, this);
  }

  public void setBairro_corresp(String value) {
    knuJNI.SintegraRN_bairro_corresp_set(swigCPtr, this, value);
  }

  public String getBairro_corresp() {
    return knuJNI.SintegraRN_bairro_corresp_get(swigCPtr, this);
  }

  public void setMunicipio_corresp(String value) {
    knuJNI.SintegraRN_municipio_corresp_set(swigCPtr, this, value);
  }

  public String getMunicipio_corresp() {
    return knuJNI.SintegraRN_municipio_corresp_get(swigCPtr, this);
  }

  public void setUf_corresp(String value) {
    knuJNI.SintegraRN_uf_corresp_set(swigCPtr, this, value);
  }

  public String getUf_corresp() {
    return knuJNI.SintegraRN_uf_corresp_get(swigCPtr, this);
  }

  public void setCep_corresp(String value) {
    knuJNI.SintegraRN_cep_corresp_set(swigCPtr, this, value);
  }

  public String getCep_corresp() {
    return knuJNI.SintegraRN_cep_corresp_get(swigCPtr, this);
  }

  public void setCnae_primario(String value) {
    knuJNI.SintegraRN_cnae_primario_set(swigCPtr, this, value);
  }

  public String getCnae_primario() {
    return knuJNI.SintegraRN_cnae_primario_get(swigCPtr, this);
  }

  public void setCnae_secundario(String value) {
    knuJNI.SintegraRN_cnae_secundario_set(swigCPtr, this, value);
  }

  public String getCnae_secundario() {
    return knuJNI.SintegraRN_cnae_secundario_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraRN_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraRN_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraRN_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraRN_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setRegime_pagamento(String value) {
    knuJNI.SintegraRN_regime_pagamento_set(swigCPtr, this, value);
  }

  public String getRegime_pagamento() {
    return knuJNI.SintegraRN_regime_pagamento_get(swigCPtr, this);
  }

  public void setTipo_contribuinte(String value) {
    knuJNI.SintegraRN_tipo_contribuinte_set(swigCPtr, this, value);
  }

  public String getTipo_contribuinte() {
    return knuJNI.SintegraRN_tipo_contribuinte_get(swigCPtr, this);
  }

  public void setCredenciamento(String value) {
    knuJNI.SintegraRN_credenciamento_set(swigCPtr, this, value);
  }

  public String getCredenciamento() {
    return knuJNI.SintegraRN_credenciamento_get(swigCPtr, this);
  }

  public void setObrigado_efd(String value) {
    knuJNI.SintegraRN_obrigado_efd_set(swigCPtr, this, value);
  }

  public String getObrigado_efd() {
    return knuJNI.SintegraRN_obrigado_efd_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraRN_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraRN_data_consulta_get(swigCPtr, this);
  }

  public void setObservacoes(String value) {
    knuJNI.SintegraRN_observacoes_set(swigCPtr, this, value);
  }

  public String getObservacoes() {
    return knuJNI.SintegraRN_observacoes_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraRN_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraRN_html_get(swigCPtr, this);
  }

  public SintegraRN() {
    this(knuJNI.new_SintegraRN(), true);
  }

}
