/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraMT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraMT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraMT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraMT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraMT_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraMT_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraMT_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraMT_desc_erro_get(swigCPtr, this);
  }

  public void setCpf_cnpj(String value) {
    knuJNI.SintegraMT_cpf_cnpj_set(swigCPtr, this, value);
  }

  public String getCpf_cnpj() {
    return knuJNI.SintegraMT_cpf_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraMT_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraMT_ie_get(swigCPtr, this);
  }

  public void setRazao_social(String value) {
    knuJNI.SintegraMT_razao_social_set(swigCPtr, this, value);
  }

  public String getRazao_social() {
    return knuJNI.SintegraMT_razao_social_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraMT_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraMT_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraMT_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraMT_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraMT_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraMT_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraMT_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraMT_bairro_get(swigCPtr, this);
  }

  public void setMunicipio_uf(String value) {
    knuJNI.SintegraMT_municipio_uf_set(swigCPtr, this, value);
  }

  public String getMunicipio_uf() {
    return knuJNI.SintegraMT_municipio_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraMT_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraMT_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraMT_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraMT_telefone_get(swigCPtr, this);
  }

  public void setCnae_fiscal(String value) {
    knuJNI.SintegraMT_cnae_fiscal_set(swigCPtr, this, value);
  }

  public String getCnae_fiscal() {
    return knuJNI.SintegraMT_cnae_fiscal_get(swigCPtr, this);
  }

  public void setCnae_secundario(String value) {
    knuJNI.SintegraMT_cnae_secundario_set(swigCPtr, this, value);
  }

  public String getCnae_secundario() {
    return knuJNI.SintegraMT_cnae_secundario_get(swigCPtr, this);
  }

  public void setCredenciado_nfe(String value) {
    knuJNI.SintegraMT_credenciado_nfe_set(swigCPtr, this, value);
  }

  public String getCredenciado_nfe() {
    return knuJNI.SintegraMT_credenciado_nfe_get(swigCPtr, this);
  }

  public void setData_obrigacao(String value) {
    knuJNI.SintegraMT_data_obrigacao_set(swigCPtr, this, value);
  }

  public String getData_obrigacao() {
    return knuJNI.SintegraMT_data_obrigacao_get(swigCPtr, this);
  }

  public void setPed(String value) {
    knuJNI.SintegraMT_ped_set(swigCPtr, this, value);
  }

  public String getPed() {
    return knuJNI.SintegraMT_ped_get(swigCPtr, this);
  }

  public void setData_ped(String value) {
    knuJNI.SintegraMT_data_ped_set(swigCPtr, this, value);
  }

  public String getData_ped() {
    return knuJNI.SintegraMT_data_ped_get(swigCPtr, this);
  }

  public void setSimples_nacional(String value) {
    knuJNI.SintegraMT_simples_nacional_set(swigCPtr, this, value);
  }

  public String getSimples_nacional() {
    return knuJNI.SintegraMT_simples_nacional_get(swigCPtr, this);
  }

  public void setMicro_empreendedor(String value) {
    knuJNI.SintegraMT_micro_empreendedor_set(swigCPtr, this, value);
  }

  public String getMicro_empreendedor() {
    return knuJNI.SintegraMT_micro_empreendedor_get(swigCPtr, this);
  }

  public void setUltrapassou_sublimite(String value) {
    knuJNI.SintegraMT_ultrapassou_sublimite_set(swigCPtr, this, value);
  }

  public String getUltrapassou_sublimite() {
    return knuJNI.SintegraMT_ultrapassou_sublimite_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraMT_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraMT_situacao_cadastral_get(swigCPtr, this);
  }

  public void setReg_fiscal_prod_primario(String value) {
    knuJNI.SintegraMT_reg_fiscal_prod_primario_set(swigCPtr, this, value);
  }

  public String getReg_fiscal_prod_primario() {
    return knuJNI.SintegraMT_reg_fiscal_prod_primario_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraMT_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraMT_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraMT_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraMT_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraMT_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraMT_html_get(swigCPtr, this);
  }

  public SintegraMT() {
    this(knuJNI.new_SintegraMT(), true);
  }

}
