/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraPI {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraPI_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraPI_cod_erro_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraPI_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraPI_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraPI_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraPI_cep_get(swigCPtr, this);
  }

  public void setCnae_primario(String value) {
    knuJNI.SintegraPI_cnae_primario_set(swigCPtr, this, value);
  }

  public String getCnae_primario() {
    return knuJNI.SintegraPI_cnae_primario_get(swigCPtr, this);
  }

  public void setCnae_secundario(String value) {
    knuJNI.SintegraPI_cnae_secundario_set(swigCPtr, this, value);
  }

  public String getCnae_secundario() {
    return knuJNI.SintegraPI_cnae_secundario_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraPI_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraPI_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraPI_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraPI_complemento_get(swigCPtr, this);
  }

  public void setData_baixa(String value) {
    knuJNI.SintegraPI_data_baixa_set(swigCPtr, this, value);
  }

  public String getData_baixa() {
    return knuJNI.SintegraPI_data_baixa_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraPI_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraPI_data_consulta_get(swigCPtr, this);
  }

  public void setData_inicio_atividade(String value) {
    knuJNI.SintegraPI_data_inicio_atividade_set(swigCPtr, this, value);
  }

  public String getData_inicio_atividade() {
    return knuJNI.SintegraPI_data_inicio_atividade_get(swigCPtr, this);
  }

  public void setData_ultima_alteracao(String value) {
    knuJNI.SintegraPI_data_ultima_alteracao_set(swigCPtr, this, value);
  }

  public String getData_ultima_alteracao() {
    return knuJNI.SintegraPI_data_ultima_alteracao_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraPI_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraPI_desc_erro_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    knuJNI.SintegraPI_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return knuJNI.SintegraPI_email_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraPI_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraPI_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraPI_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraPI_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraPI_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraPI_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraPI_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraPI_numero_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraPI_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraPI_numero_consulta_get(swigCPtr, this);
  }

  public void setObservacao(String value) {
    knuJNI.SintegraPI_observacao_set(swigCPtr, this, value);
  }

  public String getObservacao() {
    return knuJNI.SintegraPI_observacao_get(swigCPtr, this);
  }

  public void setObservacoes(String value) {
    knuJNI.SintegraPI_observacoes_set(swigCPtr, this, value);
  }

  public String getObservacoes() {
    return knuJNI.SintegraPI_observacoes_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraPI_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraPI_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraPI_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraPI_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraPI_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraPI_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraPI_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraPI_telefone_get(swigCPtr, this);
  }

  public void setUf_endereco(String value) {
    knuJNI.SintegraPI_uf_endereco_set(swigCPtr, this, value);
  }

  public String getUf_endereco() {
    return knuJNI.SintegraPI_uf_endereco_get(swigCPtr, this);
  }

  public void setUf_identificacao(String value) {
    knuJNI.SintegraPI_uf_identificacao_set(swigCPtr, this, value);
  }

  public String getUf_identificacao() {
    return knuJNI.SintegraPI_uf_identificacao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraPI_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraPI_html_get(swigCPtr, this);
  }

  public SintegraPI() {
    this(knuJNI.new_SintegraPI(), true);
  }

}
