/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraSU {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraSU(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraSU obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraSU(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraSU_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraSU_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraSU_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraSU_desc_erro_get(swigCPtr, this);
  }

  public void setInscricao(String value) {
    knuJNI.SintegraSU_inscricao_set(swigCPtr, this, value);
  }

  public String getInscricao() {
    return knuJNI.SintegraSU_inscricao_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraSU_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraSU_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraSU_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraSU_ie_get(swigCPtr, this);
  }

  public void setIe2(String value) {
    knuJNI.SintegraSU_ie2_set(swigCPtr, this, value);
  }

  public String getIe2() {
    return knuJNI.SintegraSU_ie2_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraSU_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraSU_razao_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraSU_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraSU_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraSU_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraSU_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraSU_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraSU_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraSU_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraSU_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraSU_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraSU_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraSU_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraSU_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraSU_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraSU_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraSU_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraSU_telefone_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraSU_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraSU_atividade_economica_get(swigCPtr, this);
  }

  public void setData_inscricao(String value) {
    knuJNI.SintegraSU_data_inscricao_set(swigCPtr, this, value);
  }

  public String getData_inscricao() {
    return knuJNI.SintegraSU_data_inscricao_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraSU_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraSU_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTipo_incentivo(String value) {
    knuJNI.SintegraSU_tipo_incentivo_set(swigCPtr, this, value);
  }

  public String getTipo_incentivo() {
    return knuJNI.SintegraSU_tipo_incentivo_get(swigCPtr, this);
  }

  public void setIsenta_tsa(String value) {
    knuJNI.SintegraSU_isenta_tsa_set(swigCPtr, this, value);
  }

  public String getIsenta_tsa() {
    return knuJNI.SintegraSU_isenta_tsa_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraSU_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraSU_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraSU_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraSU_html_get(swigCPtr, this);
  }

  public SintegraSU() {
    this(knuJNI.new_SintegraSU(), true);
  }

}
