/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraPB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraPB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraPB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraPB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraPB_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraPB_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraPB_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraPB_atividade_economica_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraPB_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraPB_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraPB_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraPB_cep_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraPB_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraPB_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraPB_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraPB_complemento_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraPB_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraPB_data_consulta_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraPB_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraPB_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraPB_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraPB_desc_erro_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraPB_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraPB_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraPB_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraPB_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraPB_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraPB_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraPB_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraPB_numero_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraPB_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraPB_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraPB_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraPB_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraPB_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraPB_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraPB_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraPB_telefone_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraPB_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraPB_uf_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraPB_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraPB_html_get(swigCPtr, this);
  }

  public SintegraPB() {
    this(knuJNI.new_SintegraPB(), true);
  }

}
