/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraAL {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraAL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraAL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraAL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraAL_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraAL_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraAL_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraAL_atividade_economica_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraAL_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraAL_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraAL_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraAL_cep_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraAL_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraAL_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraAL_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraAL_complemento_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraAL_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraAL_data_consulta_get(swigCPtr, this);
  }

  public void setData_ie(String value) {
    knuJNI.SintegraAL_data_ie_set(swigCPtr, this, value);
  }

  public String getData_ie() {
    return knuJNI.SintegraAL_data_ie_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraAL_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraAL_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraAL_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraAL_desc_erro_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    knuJNI.SintegraAL_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return knuJNI.SintegraAL_email_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraAL_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraAL_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraAL_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraAL_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraAL_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraAL_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraAL_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraAL_numero_get(swigCPtr, this);
  }

  public void setObservacao(String value) {
    knuJNI.SintegraAL_observacao_set(swigCPtr, this, value);
  }

  public String getObservacao() {
    return knuJNI.SintegraAL_observacao_get(swigCPtr, this);
  }

  public void setObservacoes(String value) {
    knuJNI.SintegraAL_observacoes_set(swigCPtr, this, value);
  }

  public String getObservacoes() {
    return knuJNI.SintegraAL_observacoes_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraAL_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraAL_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraAL_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraAL_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraAL_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraAL_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraAL_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraAL_telefone_get(swigCPtr, this);
  }

  public void setUf_endereco(String value) {
    knuJNI.SintegraAL_uf_endereco_set(swigCPtr, this, value);
  }

  public String getUf_endereco() {
    return knuJNI.SintegraAL_uf_endereco_get(swigCPtr, this);
  }

  public void setUf_identificacao(String value) {
    knuJNI.SintegraAL_uf_identificacao_set(swigCPtr, this, value);
  }

  public String getUf_identificacao() {
    return knuJNI.SintegraAL_uf_identificacao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraAL_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraAL_html_get(swigCPtr, this);
  }

  public SintegraAL() {
    this(knuJNI.new_SintegraAL(), true);
  }

}
