/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraPR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraPR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraPR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraPR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraPR_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraPR_cod_erro_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraPR_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraPR_desc_erro_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraPR_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraPR_cnpj_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraPR_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraPR_ie_get(swigCPtr, this);
  }

  public void setNome_empresarial(String value) {
    knuJNI.SintegraPR_nome_empresarial_set(swigCPtr, this, value);
  }

  public String getNome_empresarial() {
    return knuJNI.SintegraPR_nome_empresarial_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraPR_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraPR_logradouro_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraPR_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraPR_numero_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraPR_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraPR_complemento_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraPR_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraPR_bairro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraPR_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraPR_municipio_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraPR_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraPR_uf_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraPR_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraPR_cep_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraPR_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraPR_telefone_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    knuJNI.SintegraPR_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return knuJNI.SintegraPR_email_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraPR_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraPR_atividade_economica_get(swigCPtr, this);
  }

  public void setInicio_atividades(String value) {
    knuJNI.SintegraPR_inicio_atividades_set(swigCPtr, this, value);
  }

  public String getInicio_atividades() {
    return knuJNI.SintegraPR_inicio_atividades_get(swigCPtr, this);
  }

  public void setSituacao_atual(String value) {
    knuJNI.SintegraPR_situacao_atual_set(swigCPtr, this, value);
  }

  public String getSituacao_atual() {
    return knuJNI.SintegraPR_situacao_atual_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraPR_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraPR_situacao_cadastral_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraPR_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraPR_regime_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraPR_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraPR_data_consulta_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraPR_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraPR_html_get(swigCPtr, this);
  }

  public SintegraPR() {
    this(knuJNI.new_SintegraPR(), true);
  }

}
