/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraPA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraPA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraPA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraPA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraPA_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraPA_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraPA_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraPA_atividade_economica_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraPA_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraPA_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraPA_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraPA_cep_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraPA_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraPA_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraPA_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraPA_complemento_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraPA_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraPA_data_consulta_get(swigCPtr, this);
  }

  public void setData_inscricao(String value) {
    knuJNI.SintegraPA_data_inscricao_set(swigCPtr, this, value);
  }

  public String getData_inscricao() {
    return knuJNI.SintegraPA_data_inscricao_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraPA_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraPA_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraPA_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraPA_desc_erro_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    knuJNI.SintegraPA_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return knuJNI.SintegraPA_email_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraPA_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraPA_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraPA_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraPA_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraPA_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraPA_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraPA_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraPA_numero_get(swigCPtr, this);
  }

  public void setObservacoes(String value) {
    knuJNI.SintegraPA_observacoes_set(swigCPtr, this, value);
  }

  public String getObservacoes() {
    return knuJNI.SintegraPA_observacoes_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraPA_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraPA_razao_get(swigCPtr, this);
  }

  public void setRegime(String value) {
    knuJNI.SintegraPA_regime_set(swigCPtr, this, value);
  }

  public String getRegime() {
    return knuJNI.SintegraPA_regime_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraPA_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraPA_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraPA_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraPA_telefone_get(swigCPtr, this);
  }

  public void setUf_endereco(String value) {
    knuJNI.SintegraPA_uf_endereco_set(swigCPtr, this, value);
  }

  public String getUf_endereco() {
    return knuJNI.SintegraPA_uf_endereco_get(swigCPtr, this);
  }

  public void setUf_identificacao(String value) {
    knuJNI.SintegraPA_uf_identificacao_set(swigCPtr, this, value);
  }

  public String getUf_identificacao() {
    return knuJNI.SintegraPA_uf_identificacao_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraPA_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraPA_html_get(swigCPtr, this);
  }

  public SintegraPA() {
    this(knuJNI.new_SintegraPA(), true);
  }

}
