/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package knu;

public class SintegraMS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SintegraMS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SintegraMS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        knuJNI.delete_SintegraMS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCod_erro(int value) {
    knuJNI.SintegraMS_cod_erro_set(swigCPtr, this, value);
  }

  public int getCod_erro() {
    return knuJNI.SintegraMS_cod_erro_get(swigCPtr, this);
  }

  public void setAtividade_economica(String value) {
    knuJNI.SintegraMS_atividade_economica_set(swigCPtr, this, value);
  }

  public String getAtividade_economica() {
    return knuJNI.SintegraMS_atividade_economica_get(swigCPtr, this);
  }

  public void setBairro(String value) {
    knuJNI.SintegraMS_bairro_set(swigCPtr, this, value);
  }

  public String getBairro() {
    return knuJNI.SintegraMS_bairro_get(swigCPtr, this);
  }

  public void setCep(String value) {
    knuJNI.SintegraMS_cep_set(swigCPtr, this, value);
  }

  public String getCep() {
    return knuJNI.SintegraMS_cep_get(swigCPtr, this);
  }

  public void setCnpj(String value) {
    knuJNI.SintegraMS_cnpj_set(swigCPtr, this, value);
  }

  public String getCnpj() {
    return knuJNI.SintegraMS_cnpj_get(swigCPtr, this);
  }

  public void setComplemento(String value) {
    knuJNI.SintegraMS_complemento_set(swigCPtr, this, value);
  }

  public String getComplemento() {
    return knuJNI.SintegraMS_complemento_get(swigCPtr, this);
  }

  public void setData_consulta(String value) {
    knuJNI.SintegraMS_data_consulta_set(swigCPtr, this, value);
  }

  public String getData_consulta() {
    return knuJNI.SintegraMS_data_consulta_get(swigCPtr, this);
  }

  public void setData_situacao_cadastral(String value) {
    knuJNI.SintegraMS_data_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getData_situacao_cadastral() {
    return knuJNI.SintegraMS_data_situacao_cadastral_get(swigCPtr, this);
  }

  public void setDesc_erro(String value) {
    knuJNI.SintegraMS_desc_erro_set(swigCPtr, this, value);
  }

  public String getDesc_erro() {
    return knuJNI.SintegraMS_desc_erro_get(swigCPtr, this);
  }

  public void setIe(String value) {
    knuJNI.SintegraMS_ie_set(swigCPtr, this, value);
  }

  public String getIe() {
    return knuJNI.SintegraMS_ie_get(swigCPtr, this);
  }

  public void setLogradouro(String value) {
    knuJNI.SintegraMS_logradouro_set(swigCPtr, this, value);
  }

  public String getLogradouro() {
    return knuJNI.SintegraMS_logradouro_get(swigCPtr, this);
  }

  public void setMunicipio(String value) {
    knuJNI.SintegraMS_municipio_set(swigCPtr, this, value);
  }

  public String getMunicipio() {
    return knuJNI.SintegraMS_municipio_get(swigCPtr, this);
  }

  public void setNumero(String value) {
    knuJNI.SintegraMS_numero_set(swigCPtr, this, value);
  }

  public String getNumero() {
    return knuJNI.SintegraMS_numero_get(swigCPtr, this);
  }

  public void setNumero_consulta(String value) {
    knuJNI.SintegraMS_numero_consulta_set(swigCPtr, this, value);
  }

  public String getNumero_consulta() {
    return knuJNI.SintegraMS_numero_consulta_get(swigCPtr, this);
  }

  public void setObservacao(String value) {
    knuJNI.SintegraMS_observacao_set(swigCPtr, this, value);
  }

  public String getObservacao() {
    return knuJNI.SintegraMS_observacao_get(swigCPtr, this);
  }

  public void setRazao(String value) {
    knuJNI.SintegraMS_razao_set(swigCPtr, this, value);
  }

  public String getRazao() {
    return knuJNI.SintegraMS_razao_get(swigCPtr, this);
  }

  public void setSituacao_cadastral(String value) {
    knuJNI.SintegraMS_situacao_cadastral_set(swigCPtr, this, value);
  }

  public String getSituacao_cadastral() {
    return knuJNI.SintegraMS_situacao_cadastral_get(swigCPtr, this);
  }

  public void setTelefone(String value) {
    knuJNI.SintegraMS_telefone_set(swigCPtr, this, value);
  }

  public String getTelefone() {
    return knuJNI.SintegraMS_telefone_get(swigCPtr, this);
  }

  public void setUf(String value) {
    knuJNI.SintegraMS_uf_set(swigCPtr, this, value);
  }

  public String getUf() {
    return knuJNI.SintegraMS_uf_get(swigCPtr, this);
  }

  public void setHtml(String value) {
    knuJNI.SintegraMS_html_set(swigCPtr, this, value);
  }

  public String getHtml() {
    return knuJNI.SintegraMS_html_get(swigCPtr, this);
  }

  public SintegraMS() {
    this(knuJNI.new_SintegraMS(), true);
  }

}
