-- select 'INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES ('||id|| ',['||ds_profissao||'],['||ds_cbo||']);' from pes_profissao order by id asc;
-- select * from pes_profissao where ds_cbo is null
-- update pes_profissao set ds_cbo = '' where ds_cbo is null

INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (0,'(Indefinido)','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (1,'Acompanhantes','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (2,'Açougueiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (3,'Acupunturista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (4,'Adestrador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (5,'Administrador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (6,'Administrador de banco de dados DBA','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (7,'Administrador de redes','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (8,'Administrador público','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (9,'Advogado','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (10,'Aeromoça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (11,'Aeronauta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (12,'Aeroviário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (13,'Afiador de ferramentas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (14,'Agente comunitário de saúde','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (15,'Agente de combate à endemias','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (16,'Agente de defesa sanitária','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (17,'Agente de defesa sanitária animal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (18,'Agente de redução de danos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (19,'Agente de viagens','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (20,'Agente funerário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (21,'Agente penitenciário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (22,'Agricultor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (23,'Agrimensor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (24,'Agrônomo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (25,'Ajudante de produção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (26,'Alergologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (27,'Alfaiate','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (28,'Almirante da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (29,'Almoxarife','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (30,'Alpinista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (31,'Ambientalista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (32,'Ambulante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (33,'Amolador de ferramentas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (34,'Analista de sistemas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (35,'Anestesiologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (36,'Angiologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (37,'Antropólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (38,'Apicultor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (39,'Apontador de mão-de-obra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (40,'Apresentador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (41,'Árbitro e mediador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (42,'Argumentista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (43,'Armador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (44,'Armeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (45,'Arqueólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (46,'Arquiteto','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (47,'Arquivista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (48,'Arranjador musical','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (49,'Arrumadeira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (50,'Artesão','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (51,'Artista de circo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (52,'Artista plástico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (53,'Artista/Técnico em espetáculos de diversões','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (54,'Ascensorista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (56,'Aspirante a Oficial do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (57,'Aspirante da aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (58,'Assessor de imprensa','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (59,'Assessor parlamentar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (60,'Assistente de câmera','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (61,'Assistente de direção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (62,'Assistente de produção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (63,'Assistente social','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (64,'Astrofísico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (65,'Astrólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (66,'Astronauta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (67,'Astrônomo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (68,'Atendente','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (69,'Atleta de arremesso de peso','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (70,'Atleta de canoagem','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (71,'Atleta de nado sincronizado','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (72,'Atleta de tiro com arco','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (73,'Ator','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (74,'Atuário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (75,'Auditor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (76,'Auxiliar de reprografia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (77,'Auxiliar de serviços gerais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (78,'Auxiliar ou assistente administrativo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (79,'Avalista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (80,'Aviador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (81,'Babá ou Babysitter','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (82,'Bailarina','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (83,'Baixista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (84,'Balconista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (85,'Bancário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (86,'Barbeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (87,'Barista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (88,'Barman','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (89,'Bartender','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (90,'Baterista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (91,'Bedel','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (92,'Berçarista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (93,'Bibliotecário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (94,'Biblioteconomista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (95,'Biólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (96,'Biomédico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (97,'Bioquímico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (98,'Biotecnólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (99,'Bóia-fria','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (100,'Bombeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (101,'Borracheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (102,'Boticário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (103,'Boxeador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (104,'Brigadeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (105,'Broker/Corretor da bolsa de valores','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (106,'Cabeleireiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (107,'Cabo da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (108,'Cabo da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (109,'Cabo do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (110,'Caça-talentos/Olheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (111,'Cadeirinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (112,'Cadista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (113,'Caixa','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (114,'Caldeireiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (115,'Cambista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (116,'Camelô','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (117,'Cameraman','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (118,'Caminhoneiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (119,'Cancerologista ou Oncologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (120,'Cantor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (121,'Capataz','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (122,'Capelão','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (123,'Capitão da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (124,'Capitão da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (125,'Capitão do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (126,'Capoeirista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (127,'Cardiologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (128,'Carnavalesco','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (129,'Carpinteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (130,'Cartazeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (131,'Carteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (132,'Cartógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (133,'Cartunista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (134,'Catador de carangueijos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (135,'Catador de material reciclável','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (136,'Cenógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (137,'Cenotécnico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (138,'Ceramista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (139,'Cerimonialista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (140,'Chapeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (141,'Chargista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (142,'Chaveiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (143,'Chefe de cozinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (144,'Ciclista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (145,'Cientista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (146,'Cientista da informação e documentação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (147,'Cientista de alimentos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (148,'Cientista político','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (149,'Cientista social','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (150,'Cineasta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (151,'Cinegrafista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (152,'Cinematográfo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (153,'Cirurgião bucal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (154,'Cirurgião dentista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (155,'Clap loader','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (156,'Clarinetista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (157,'Classificador contábil','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (158,'Clínico geral','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (159,'Coach','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (160,'Cobaia Médica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (161,'Cobrador de ônibus','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (162,'Cobrador de pedágio','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (163,'Coloproctologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (164,'Comandante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (165,'Comerciante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (166,'Comissário de bordo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (167,'Compositor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (168,'Comprador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (169,'Confeiteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (170,'Conferente de carga e descarga','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (171,'Conferente de expedição','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (172,'Conferente de recebimento','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (173,'Construtor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (174,'Consultor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (175,'Consultor de moda','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (176,'Consultor de radiestesia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (177,'Contábil','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (178,'Contabilista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (179,'Contador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (180,'Contatólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (181,'Continuista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (182,'Contra regra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (183,'Contramestre em transporte marítimo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (184,'Controlador de vôo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (185,'Controller','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (186,'Coordenador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (187,'Copeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (188,'Co-piloto','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (189,'Coreógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (190,'Coronel da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (191,'Coronel do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (192,'Corredor de atletismo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (193,'Corregedor de justiça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (194,'Corretor da bolsa de valores','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (195,'Corretor de imóveis','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (196,'Corretor de seguros','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (197,'Cortador de cana-de-açucar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (198,'Costureira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (199,'Coveiro ou sepultador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (200,'Cozinheira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (201,'Crítico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (202,'Cumim','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (203,'Dançarino','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (204,'Datilógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (205,'Dedetizador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (206,'Defensor Público','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (207,'Degustador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (208,'Delegado','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (209,'Dentista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (210,'Deputado','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (211,'Dermatologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (212,'Desembargador de justiça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (213,'Desenhista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (214,'Designer de interiores','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (215,'Designer de jóia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (216,'Designer de moda','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (217,'Designer de produto ou desenhista industrial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (218,'Designer gráfico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (219,'Despachante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (220,'Diagramador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (221,'Dialoguista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (222,'Diarista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (223,'Digitador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (224,'Diplomata','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (225,'Diretor de cinema','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (226,'Diretor de fotografia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (227,'Diretor de produção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (228,'DJ','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (229,'Dogueiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (230,'Dublador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (231,'Dublê','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (232,'Ecólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (233,'Economista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (234,'Economista doméstico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (235,'Editor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (236,'Editor de mesa de corte','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (237,'Educador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (238,'Educador integrado à saúde pública','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (239,'Eletricista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (240,'Eletricista de automóveis','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (241,'Embaixador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (242,'Embalador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (243,'Embalsamador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (244,'Empacotador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (245,'Empregado doméstico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (246,'Empresário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (247,'Encanador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (248,'Encarregado de manutenção predial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (249,'Endocrinologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (250,'Endodontista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (251,'Enfermeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (252,'Engenheiro acústico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (253,'Engenheiro aeronáutico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (254,'Engenheiro agrícola','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (255,'Engenheiro agrimensor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (256,'Engenheiro agrônomo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (257,'Engenheiro ambiental','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (258,'Engenheiro cartográfico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (259,'Engenheiro civil','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (260,'Engenheiro de alimentos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (261,'Engenheiro de aquicultura','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (262,'Engenheiro de biossistemas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (263,'Engenheiro de computação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (264,'Engenheiro de controle e automação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (265,'Engenheiro de energia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (266,'Engenheiro de ergonomia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (267,'Engenheiro de horticultura','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (268,'Engenheiro de iluminação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (269,'Engenheiro de manufatura','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (270,'Engenheiro de materiais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (271,'Engenheiro de minas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (272,'Engenheiro de petróleo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (273,'Engenheiro de processos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (274,'Engenheiro de produção agroindustrial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (275,'Engenheiro de produto ou produção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (276,'Engenheiro de projetos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (277,'Engenheiro de segurança do trabalho','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (278,'Engenheiro de som','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (279,'Engenheiro de supply chain ou logística','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (280,'Engenheiro de telecomunicações','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (281,'Engenheiro de transportes','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (282,'Engenheiro elétrico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (283,'Engenheiro físico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (284,'Engenheiro florestal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (285,'Engenheiro industrial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (286,'Engenheiro mecânico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (287,'Engenheiro mecatrônico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (288,'Engenheiro metalúrgico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (289,'Engenheiro naval','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (290,'Engenheiro petroquímico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (291,'Engenheiro químico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (292,'Engenheiro sanitarista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (293,'Engenheiro têxtil','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (294,'Engraxate','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (295,'Enólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (296,'Entalhador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (297,'Epidemiologista ou epidemiólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (298,'Escoteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (300,'Escritor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (301,'Escriturário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (302,'Escrivão','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (303,'Escultor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (304,'Esgrimista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (305,'Especialista em agronegócios','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (306,'Espeleologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (307,'Estampador de tecidos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (308,'Estatístico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (309,'Esteticista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (310,'Estilista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (311,'Estivador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (312,'Estofador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (313,'Estoquista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (314,'Farmacêutico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (315,'Faturista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (316,'Faxineiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (317,'Feirante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (318,'Ferramenteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (319,'Ferreiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (320,'Ferroviário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (321,'Figurante','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (322,'Figurinista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (323,'Filósofo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (324,'Fiscal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (325,'Físico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (326,'Físico nuclear','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (327,'Fisiculturista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (328,'Fisioterapeuta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (329,'Flanelinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (330,'Flautista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (331,'Florista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (332,'Fonoaudiólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (333,'Forneiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (334,'Fotógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (335,'Frentista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (336,'Fresador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (337,'Fundidor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (338,'Fundidor de placa de gesso','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (339,'Funileiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (340,'Gagsman','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (341,'Gandula','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (342,'Garçom','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (343,'Gari','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (344,'Garimpeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (345,'Gastroenterologista ou Gastrenterologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (346,'Gastrônomo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (347,'General do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (348,'Geofísico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (349,'Geógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (350,'Geólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (351,'Geradorista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (352,'Gerente de banco','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (353,'Gerente de inovações ou novos negócios','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (354,'Gerente de riscos em seguros','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (355,'Gerente de vendas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (356,'Geriatra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (357,'Gestor ambiental','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (358,'Gestor de qualidade','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (359,'Gestor de recursos humanos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (360,'Gestor de tecnologia da informação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (361,'Gestor público','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (362,'Ginasta artística','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (363,'Ginasta rítmica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (364,'Ginecologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (365,'Gourmet','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (366,'Governador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (367,'Governanta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (368,'Grafologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (369,'Gravurista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (370,'Guarda ou policial rodoviário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (371,'Guarda roupeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (372,'Guardador de veículos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (373,'Guarda-vidas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (374,'Guia turistico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (375,'Guincheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (376,'Guitarrista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (377,'Harpista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (378,'Headhunter','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (379,'Hematologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (380,'Historiador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (381,'Homeopata','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (382,'Hostess','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (383,'Ilustrador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (384,'Implantodontista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (385,'Impressor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (386,'Imunologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (387,'Infectologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (388,'Inspetor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (389,'Instalador de linha telefônica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (390,'Instalador de painéis','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (391,'Instrumentador cirúrgico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (392,'Instrumentista musical','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (393,'Instrutor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (394,'Intérprete','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (395,'Intérprete de Bíblias','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (396,'Intérprete e tradutor de língua de sinais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (397,'Investigador de Polícia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (398,'Investigador particular','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (399,'Jangadeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (400,'Jardineiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (401,'Jogador de badminton','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (402,'Jogador de basquete','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (403,'Jogador de bocha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (404,'Jogador de boliche','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (405,'Jogador de futebol','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (406,'Jogador de golfe','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (407,'Jogador de handebol','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (408,'Jogador de hóquei','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (409,'Jogador de tênis de mesa','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (410,'Jogador de vôlei','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (411,'Jóquei','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (412,'Jornaleiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (413,'Jornalista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (414,'Judoca','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (415,'Juiz de direito','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (416,'Juiz de futebol','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (417,'Juiz ou árbitro de futebol','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (418,'Karateca','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (419,'Kite-surfer','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (420,'Laboratorista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (421,'Lactarista hospitalar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (422,'Lamboteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (423,'Lancheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (424,'Lanterneiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (425,'Lapidário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (426,'Lavador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (427,'Lavador de veículos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (428,'Leão de chácara','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (429,'Leiloeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (430,'Leiteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (431,'Lenhador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (432,'Letrista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (433,'Levantador de peso','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (434,'Líder comunitário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (435,'Limpador de vidros','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (436,'Lixeiro/Coletor de lixo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (437,'Locutor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (438,'Lubrificador de máquinas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (439,'Lutador de jiu-jitsu','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (440,'Lutador de karatê','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (441,'Lutador de kung fu','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (442,'Lutador de luta livre','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (443,'Lutador de taekwondo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (444,'Luthier','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (445,'Mãe social','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (446,'Maestro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (447,'Mágico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (448,'Maitre','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (449,'Major da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (450,'Major do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (451,'Manicure','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (452,'Manobrista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (453,'Maquiador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (454,'Maquinista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (455,'Marcador de luz','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (456,'Marceneiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (457,'Marechal do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (458,'Marechal-do-Ar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (459,'Marinheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (460,'Marketeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (461,'Massagista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (462,'Massoterapeuta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (463,'Matemático','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (464,'Mecânico de automóveis','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (465,'Mecânico de vôo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (466,'Mecanógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (467,'Médico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (468,'Médico cirurgião','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (469,'Médico geneticista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (470,'Médico legista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (471,'Médico nuclear','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (472,'Meeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (473,'Mensageiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (474,'Meredeira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (475,'Mergulhador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (476,'Mestre cervejeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (477,'Mestre-de-obras','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (478,'Metalúrgico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (479,'Meteorologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (480,'Microfonista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (481,'Militar da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (482,'Militar da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (483,'Militar do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (484,'Ministro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (485,'Modelista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (486,'Modelo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (487,'Moldador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (488,'Moldureiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (489,'Moleiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (490,'Montador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (491,'Montador de negativos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (492,'Motofrete','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (493,'Motorista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (494,'Mototaxista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (495,'Museólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (496,'Músico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (497,'Musicoterapeuta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (498,'Nadador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (499,'Naturólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (500,'Navegador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (501,'Necromaquiador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (502,'Nefrologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (503,'Neonatologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (504,'Neurocirurgião','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (505,'Neurologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (506,'Notário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (507,'Numerólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (508,'Nutricionista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (509,'Nutrologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (510,'Obstetra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (511,'Oceanógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (512,'Oculista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (513,'Odontologista estético','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (514,'Odontologista legal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (515,'Odontologista preventivo e social','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (516,'Odontopediatra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (517,'Office-boy','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (518,'Oficial de justiça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (519,'Oftalmologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (520,'Ombudsman','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (521,'Operador de bombas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (522,'Operador de telemarketing','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (523,'Operador de vídeo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (524,'Optometrista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (525,'Orçamentista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (526,'Orientador educacional','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (527,'Ortesista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (528,'Ortodontista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (529,'Ortopedista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (530,'Ortoptista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (531,'Otorrinolaringologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (532,'Ourives','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (533,'Paginador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (534,'Paisagista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (535,'Panfleteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (536,'Panificador/Padeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (537,'Paparazzo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (538,'Papiloscopista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (539,'Paramédico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (540,'Pára-quedista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (541,'Parteira tradicional','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (542,'Passador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (543,'Pastilheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (544,'Patinador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (545,'Patologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (546,'Patologista oral','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (547,'Peão de rodeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (548,'Pecuarista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (549,'Pedagogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (550,'Pediatra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (551,'Pedicure','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (552,'Pedreiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (553,'Peixeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (554,'Penhorista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (555,'Percursionista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (556,'Perfumista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (557,'Perfusionista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (558,'Perito criminal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (559,'Perito judicial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (560,'Personal stylist','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (561,'Personal trainer','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (562,'Pescador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (563,'Pesquisador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (564,'Petroleiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (565,'Pianista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (566,'Piloto automobilístico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (567,'Piloto de avião','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (568,'Pintor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (569,'Pizzaiolo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (570,'Plastimodelista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (571,'Pneumologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (572,'Podólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (573,'Policial civil','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (574,'Policial federal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (575,'Policial militar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (576,'Polidor de produção','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (577,'Político','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (578,'Porteiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (579,'Portuário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (580,'Prático','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (581,'Prefeito','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (582,'Prensista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (583,'Preparador de máquinas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (584,'Presidente da República','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (585,'Procurador de justiça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (586,'Produtor de audio visual','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (587,'Produtor de eventos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (588,'Produtor de multimídia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (589,'Produtor editorial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (590,'Produtor fonográfico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (591,'Produtor musical','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (592,'Professor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (593,'Profissional de áudio','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (594,'Profissional de cinema','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (595,'Profissional de comércio exterior','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (596,'Profissional de educação física','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (597,'Profissional de efeitos especiais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (598,'Profissional de hotelaria','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (599,'Profissional de informática','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (600,'Profissional de linguística','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (601,'Profissional de logística','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (602,'Profissional de manutenção industrial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (603,'Profissional de marketing','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (604,'Profissional de rádio e tv','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (605,'Profissional de reciclagem','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (606,'Profissional de recursos humanos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (607,'Profissional de relacionamento com investidores RI','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (608,'Profissional de relações internacionais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (609,'Profissional de relações públicas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (610,'Profissional de tecnologia de laticínios','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (611,'Programador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (612,'Projetista mecânico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (613,'Promotor de eventos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (614,'Promotor de vendas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (615,'Promotor público/de justiça','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (616,'Protesista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (617,'Protético dentário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (618,'Psicólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (619,'Psicomotricista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (620,'Psicopedagogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (621,'Psiquiatra','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (622,'Publicitário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (623,'Quadrinista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (624,'Químico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (625,'Químico farmacêutico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (626,'Quiropraxista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (627,'Quitandeiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (628,'Radialista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (629,'Radialista programador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (630,'Radiologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (631,'Radiooperador de vôo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (632,'Radioterapêutico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (633,'Rebarbador de metal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (634,'Recepcionista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (635,'Recreador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (636,'Redator','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (637,'Regente','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (638,'Relações públicas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (639,'Remador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (640,'Repórter','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (641,'Repositor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (642,'Representante comercial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (643,'Restaurador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (644,'Retificador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (645,'Reumatologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (646,'Revendedor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (647,'Revisor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (648,'Roteirista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (649,'Sacoleira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (650,'Salgadeira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (651,'Salva-vidas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (652,'Sapateiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (653,'Sargento da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (654,'Sargento da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (655,'Sargento do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (656,'Saxofonista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (657,'Secretária','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (658,'Seguidor de compras','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (659,'Segurança particular','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (660,'Selecionador de pessoal','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (661,'Senador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (662,'Separador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (663,'Seringueiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (664,'Serralheiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (665,'Servente-de-obras','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (666,'Serventuário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (667,'Sexólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (668,'Síndico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (669,'Skatista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (670,'Sociólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (671,'Soldado da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (672,'Soldador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (673,'Somelier','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (674,'Sonoplasta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (675,'Subprefeito','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (676,'Subtenente do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (677,'Supervisor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (678,'Surfista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (679,'Sushiman','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (680,'Tabelião','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (681,'Taifeiro da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (682,'Taifeiro do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (683,'Tapeceiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (684,'Tatuador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (685,'Taxidermista ou Embalsamador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (686,'Taxista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (687,'Tecelão','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (688,'Técnico de gesso','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (689,'Técnico de som','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (690,'Técnico em agropecuária','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (691,'Técnico em arquivo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (692,'Técnico em aviação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (693,'Técnico em desporto','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (694,'Técnico em documentação','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (695,'Técnico em edificações','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (696,'Técnico em hardware','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (697,'Técnico em higiene dentária','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (698,'Técnico em óptica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (699,'Técnico em radiologia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (700,'Técnico em rede','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (701,'Técnico em segurança do trabalho','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (702,'Técnico em taquigrafia','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (703,'Técnico em tratamento de água','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (704,'Técnico tributarista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (705,'Tecnólogo em automação industrial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (706,'Tecnólogo em ciências das plantas medicinais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (707,'Tecnólogo em desenvolvimento social','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (708,'Tecnólogo em esporte e lazer','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (709,'Tecnólogo em geoprocessamento','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (710,'Tecnólogo em irrigação e drenagem','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (711,'Tecnólogo em jogos dogitais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (712,'Tecnólogo em navegação fluvial','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (713,'Tecnólogo em negócios imobiliários','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (714,'Tecnólogo em papel e celulose','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (715,'Tecnólogo em processos químicos','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (716,'Tecnólogo em produção de bebidas','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (717,'Tecnólogo em produção moveleira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (718,'Tecnólogo em produção sucroalcooleira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (719,'Tecnólogo em recursos pesqueiros','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (720,'Tecnólogo em rochas ornamentais','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (721,'Tecnólogo em silvicultura','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (722,'Tecnólogo em tecnologia da madeira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (723,'Telefonista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (724,'Telegrafista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (725,'Tenente da Aeronáutica','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (726,'Tenente da Marinha','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (727,'Tenente do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (728,'Tenente-Coronel do Exército','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (729,'Tenista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (730,'Teólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (731,'Terapeuta floral','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (732,'Terapeuta Holístico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (733,'Terapeuta ocupacional','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (734,'Tesoureiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (735,'Timoneiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (736,'Tintureiro','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (737,'Topógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (738,'Torneiro mecânico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (739,'Torreiro/Torrista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (740,'Tosador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (741,'Toxicologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (742,'Tradutor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (743,'Transcritor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (744,'Transportador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (745,'Traumatologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (746,'Treinador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (747,'Triatleta','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (748,'Trilheiro ou músico de cinema','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (749,'Trompetista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (750,'Turismólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (751,'Ufólogo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (752,'Urbanista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (753,'Urologista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (754,'Velejador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (755,'Vendedor','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (756,'Ventríloquo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (757,'Vereador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (758,'Veterinário','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (759,'Vigia parlamentar','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (760,'Vigilante noturno/diurno','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (761,'Violonista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (762,'Vistoriador de sinistros','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (763,'Viveirista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (764,'Webdesigner','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (765,'Webmaster','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (766,'Windsurfer','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (767,'Xilógrafo','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (768,'Zelador','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (769,'Zootecnista','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (770,'Gerente','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (771,'Técnico','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (772,'Assistente','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (773,'Controle de Qualidade','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (774,'Operador de empilhadeira','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (806,'DIRETOR','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (807,'VENDEDORA','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (808,'AUX. ADMINISTRATIVO','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (809,'OP. DE ATENDIMENTO','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (810,'INSTALADOR','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (811,'ASSISTENTE DE VENDAS','');
INSERT INTO pes_profissao (id, ds_profissao, ds_cbo) VALUES (814,'Operadora','');
SELECT setval('pes_profissao_id_seq', max(id)) FROM pes_profissao;