INSERT INTO seg_departamento (id, ds_descricao) SELECT 1, 'CPD'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 1);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 2, 'Financeiro'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 2);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 3, 'RH'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 3);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 4, 'Secretaría'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 4);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 5, 'Diretoria'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 5);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 6, 'Social'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 6);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 7, 'Gerencia'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 7);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 8, 'Homologação'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 8);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 9, 'Jurídico'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 9);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 10, 'Recepção Sede'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 10);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 11, 'Recepção Academia'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 11);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 12, 'Recepção Clube'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 12);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 13, 'Recepção Escola'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 13);
INSERT INTO seg_departamento (id, ds_descricao) SELECT 14, 'Arrecadação'   WHERE NOT EXISTS ( SELECT id FROM seg_departamento WHERE id = 14);
SELECT setval('seg_departamento_id_seq', max(id)) FROM seg_departamento;