-- sis_relatorios 
-- Criate: 2013-08-07
-- Last edition: 2013-08-07 - by: Bruno Vieira

INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 1,'Contribuintes','/Relatorios/CONTRIBUINTES.jasper',5,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 1);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 2,'Contribuintes(Paisagem)','/Relatorios/CONTRIBUINTESPAISAGEM.jasper',5,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 2);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 3,'Contribuintes por Escritório Alfabético','/Relatorios/CONTRIBUINTESPORESCRITORIO.jasper',5,'conpes.ds_nome,conpes.id,p.ds_nome','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 3);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 4,'Etiqueta','/Relatorios/ETCONTRIBUINTES6181.jasper',5,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 4);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 5,'Escritórios','/Relatorios/ESCRITORIOS.jasper',6,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 5);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 6,'Etiquetas','/Relatorios/ETESCRITORIO6181.jasper',6,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 6);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 7,'Extrato de Arrecadação','/Relatorios/EXTRATO_ARRECADACAO.jasper',110,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 7);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 8,'Extrato de Arrecadação por Escritório','/Relatorios/EXTRATO_ARRECADACAO_ESCRITORIO.jasper',110,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 8);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 9,'Extrato de Arrecadação por Empresa','/Relatorios/EXTRATO_ARRECADACAO_EMPRESA.jasper',110,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 9);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 10,'Relação de Sócios','/Relatorios/SOCIOS.jasper',171,'','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 10);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 11,'Registro de Associados','/Relatorios/REGISTRO_DE_ASSOCIADOS.jasper',171,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 11);  
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 12,'Sócios por Empresa','/Relatorios/SOCIOS_EMPRESA.jasper',171,'p.empresa, p.cnpj','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 12);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 13,'Sócios por Empresa com Assinatura','/Relatorios/SOCIOS_EMPRESA_ASSINATURA.jasper',171,'p.empresa, p.cnpj','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 13);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 14,'Etiquetas Sócios','/Relatorios/ETIQUETA_SOCIO.jasper',171,'','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 14);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 15,'Etiqueta Sócio Individual','/Relatorios/ETIQUETA_TERMICA_SOCIAL_RETRATO.jasper',171,'','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 15);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 16,'Sócios por Empresa Paisagem','/Relatorios/SOCIOS_EMPRESA_PAISAGEM.jasper',171,'p.empresa,p.cnpj','so.inativacao is null' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 16);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 17,'Contribuintes/Email','/Relatorios/CONTRIBUINTES_EMAIL.jasper',5,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 17);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 18,'Escritórios/Email','/Relatorios/ESCRITORIOS_EMAIL.jasper',6,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 18);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 19,'Relatório de Homologação','/Relatorios/HOMOLOGACAO.jasper',177,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 19);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 20,'Extrato com Valor Líquido','/Relatorios/EXTRATO_ARRECADACAO_LIQUIDO.jasper',110,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 20);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 21,'Contribuintes por Escritório Endereço','/Relatorios/CONTRIBUINTESPORESCRITORIO.jasper',5,'ccon.ds_uf,ccon.ds_cidade,bcon.ds_descricao,decon.ds_descricao,pecon.ds_numero,conpes.ds_nome,conpes.id,p.ds_nome','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 21);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 22,'Convites Clube','/Relatorios/RELATORIO_CONVITES_CLUBE.jasper', 226,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 22);
INSERT INTO sis_relatorios (id, ds_nome, ds_jasper, id_rotina, ds_qry_ordem, ds_qry) SELECT 23,'Oposição','/Relatorios/RELATORIO_OPOSICAO.jasper', 239,'','' WHERE NOT EXISTS ( SELECT id FROM sis_relatorios WHERE id = 23);
SELECT setval('sis_relatorios_id_seq', max(id)) FROM sis_relatorios;
